import {randomUUID} from 'crypto';
import db from '../database/database';
import {ANOMALIES,RARE_DUTIES} from '../config/ActivityCatalog';
import {inventoryRepository} from '../database/repositories/InventoryRepository';
import {runtimeKernel} from './RuntimeKernelService';

const now=()=>Date.now();
function vn(at=now()){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(at)).map(x=>[x.type,x.value]));return{date:`${parts.year}-${parts.month}-${parts.day}`,weekday:parts.weekday,hour:+parts.hour,minute:+parts.minute,week:Math.floor(at/(7*86400_000))}}
function context(uid:string){return{confirmedFacts:(db.prepare("SELECT COUNT(*) n FROM knowledge_provenance WHERE user_id=? AND confidence IN ('confirmed','supported')").get(uid) as any).n,investigationClears:(db.prepare("SELECT COUNT(*) n FROM duty_assignments WHERE user_id=? AND duty_type='dieu_tra' AND status='CLAIMED'").get(uid) as any).n,anomalyClears:(db.prepare("SELECT COUNT(*) n FROM anomaly_participation WHERE user_id=? AND status='CLAIMED'").get(uid) as any).n,dutyTypes:(db.prepare("SELECT COUNT(DISTINCT duty_type) n FROM duty_assignments WHERE user_id=? AND status='CLAIMED'").get(uid) as any).n,farmHarvests:(db.prepare("SELECT COUNT(*) n FROM storage_craft_log WHERE user_id=? AND outcome='HARVEST'").get(uid) as any).n,knowsDiemLinh:!!db.prepare("SELECT 1 FROM player_npc_knowledge WHERE user_id=? AND npc_id IN ('ky_hoai_chau','tham_thanh_chi')").get(uid),secretRealmClears:(db.prepare('SELECT COALESCE(SUM(clears),0) n FROM secret_realm_log WHERE user_id=?').get(uid) as any).n,realmRank:Math.floor(Number((db.prepare('SELECT level FROM users WHERE discord_id=?').get(uid) as any)?.level||1)/10),travelEntries:(db.prepare('SELECT COUNT(*) n FROM travel_log_entries WHERE user_id=?').get(uid) as any).n,sharedMemories:(db.prepare('SELECT COUNT(*) n FROM npc_memories WHERE user_id=?').get(uid) as any).n,hoSinhDone:(db.prepare("SELECT COUNT(*) n FROM duty_assignments WHERE user_id=? AND duty_type='ho_sinh' AND status='CLAIMED'").get(uid) as any).n,companionMet:!!db.prepare('SELECT 1 FROM player_npc_knowledge WHERE user_id=?').get(uid),tranNhieuDone:(db.prepare("SELECT COUNT(*) n FROM duty_assignments WHERE user_id=? AND duty_type='tran_nhieu' AND status='CLAIMED'").get(uid) as any).n,craftLevel:Number((db.prepare('SELECT MAX(level) n FROM craft_mastery WHERE user_id=?').get(uid) as any)?.n||0),tamNhanDone:(db.prepare("SELECT COUNT(*) n FROM duty_assignments WHERE user_id=? AND duty_type='tam_nhan' AND status='CLAIMED'").get(uid) as any).n,worldEventContrib:(db.prepare('SELECT COUNT(*) n FROM world_event_scores WHERE user_id=? AND score>0').get(uid) as any).n}}
export const rareDutyRuntime={
 discover(uid:string){const ctx=context(uid),out:any[]=[];for(const d of RARE_DUTIES){const state=db.prepare('SELECT * FROM rare_duty_states WHERE user_id=? AND duty_id=?').get(uid,d.id) as any;if(state){out.push({...d,state:state.state,currentNode:state.current_node});continue}if(d.trigger(ctx)){db.prepare("INSERT INTO rare_duty_states(user_id,duty_id,state,current_node,definition_version,created_at,updated_at) VALUES(?,?,'AVAILABLE',?,1,?,?)").run(uid,d.id,d.nodes[0],now(),now());out.push({...d,state:'AVAILABLE',currentNode:d.nodes[0]})}}return out},
 addEvidence(uid:string,dutyId:string,group:string,sourceRef:string,receiptKey:string){const d=RARE_DUTIES.find(x=>x.id===dutyId);if(!d?.evidence||!d.evidence.groups[group])return{ok:false,message:'Nhóm chứng cứ không thuộc hồ sơ này.'};const state=db.prepare('SELECT * FROM rare_duty_states WHERE user_id=? AND duty_id=?').get(uid,dutyId) as any;if(!state)return{ok:false,message:'Nghĩa vụ chưa được mở từ nguồn hợp lệ.'};return runtimeKernel.execute(receiptKey,'RARE_DUTY',uid,'EVIDENCE',()=>{db.prepare('INSERT INTO rare_duty_evidence(user_id,duty_id,evidence_group,source_ref,receipt_key,created_at) VALUES(?,?,?,?,?,?)').run(uid,dutyId,group,sourceRef,receiptKey,now());const rows=db.prepare('SELECT DISTINCT evidence_group FROM rare_duty_evidence WHERE user_id=? AND duty_id=?').all(uid,dutyId) as any[];db.prepare("UPDATE rare_duty_states SET state=?,current_node='DOI_CHIEU',evidence_json=?,updated_at=? WHERE user_id=? AND duty_id=?").run(rows.length>=d.evidence!.required?'READY':'ACTIVE',JSON.stringify(rows.map(x=>x.evidence_group)),now(),uid,dutyId);return{ok:true,count:rows.length,required:d.evidence!.required,message:`Đã xác lập ${rows.length}/${d.evidence!.required} nhóm chứng cứ.`}}).value},
 resolve(uid:string,dutyId:string,receiptKey:string){const d=RARE_DUTIES.find(x=>x.id===dutyId),s=db.prepare('SELECT * FROM rare_duty_states WHERE user_id=? AND duty_id=?').get(uid,dutyId) as any;if(!d||!s||s.state==='RESOLVED'||(d.evidence&&s.state!=='READY'))return{ok:false,message:'Nghĩa vụ chưa đủ điều kiện kết luận.'};return runtimeKernel.execute(receiptKey,'RARE_DUTY',uid,'RESOLVE',()=>{const add=d.reward.item?inventoryRepository.add(uid,d.reward.item,1):{overflow:0};db.prepare('UPDATE users SET coin_ha_pham=coin_ha_pham+?,tu_vi=tu_vi+?,knb=knb+? WHERE discord_id=?').run(d.reward.lt,d.reward.tuvi,d.reward.cplt,uid);db.prepare("UPDATE rare_duty_states SET state='RESOLVED',current_node=?,updated_at=?,resolved_at=? WHERE user_id=? AND duty_id=?").run(d.nodes.at(-1),now(),now(),uid,dutyId);return{ok:true,overflow:add.overflow,message:`Đã hoàn tất ${d.title}; vật phẩm ${add.overflow?'vào Tạm Nang':'vào hành trang'}.`}}).value}
};

export const anomalyRuntime={
 tick(at=now()){const z=vn(at);if(z.weekday!=='Thu'||z.hour<19||(z.hour===19&&z.minute<30))return[];const idx=((z.week%ANOMALIES.length)+ANOMALIES.length)%ANOMALIES.length,a=ANOMALIES[idx],start=at-((z.hour-19)*60+z.minute-30)*60_000,end=start+90*60_000;if(at>=end)return[];const key=`${a.id}:${z.date}`,id=randomUUID(),r=db.prepare("INSERT OR IGNORE INTO anomaly_runs(id,anomaly_id,scheduled_key,state,definition_version,starts_at,ends_at,state_json,created_at,updated_at) VALUES(?,?,?,'ACTIVE',1,?,?,?, ?,?)").run(id,a.id,key,start,end,JSON.stringify({encounters:a.encounters}),at,at);db.prepare("UPDATE anomaly_runs SET state='CLOSED',updated_at=? WHERE state='ACTIVE' AND ends_at<=?").run(at,at);return r.changes?[a.name]:[]},
 active(){return db.prepare("SELECT * FROM anomaly_runs WHERE state='ACTIVE' AND ends_at>?").all(now()) as any[]},
 act(uid:string,runId:string){const run=db.prepare("SELECT * FROM anomaly_runs WHERE id=? AND state='ACTIVE' AND ends_at>?").get(runId,now()) as any,a=run&&ANOMALIES.find(x=>x.id===run.anomaly_id);if(!run||!a)return{ok:false,message:'Dị Tượng không còn hoạt động.'};const receipt=`anomaly:${runId}:${uid}:claim`;const row=db.prepare('SELECT * FROM anomaly_participation WHERE run_id=? AND user_id=?').get(runId,uid) as any,progress=Math.min(3,(row?.progress||0)+1);db.prepare('INSERT INTO anomaly_participation(run_id,user_id,objective,progress,status,updated_at) VALUES(?,?,?,?,\'ACTIVE\',?) ON CONFLICT(run_id,user_id) DO UPDATE SET progress=excluded.progress,updated_at=excluded.updated_at').run(runId,uid,a.objective,progress,now());if(progress<3)return{ok:true,message:`Đã hoàn thành ${progress}/3 phân đoạn ${a.objective}.`};return runtimeKernel.execute(receipt,'ANOMALY',uid,'SETTLE',()=>{const add=inventoryRepository.add(uid,a.reward.item,1);db.prepare('UPDATE users SET coin_ha_pham=coin_ha_pham+?,tu_vi=tu_vi+?,knb=knb+? WHERE discord_id=?').run(a.reward.lt,a.reward.tuvi,a.reward.cplt,uid);db.prepare("UPDATE anomaly_participation SET status='CLAIMED',receipt_key=?,updated_at=? WHERE run_id=? AND user_id=?").run(receipt,now(),runId,uid);db.prepare('INSERT INTO world_merit_ledger(receipt_key,user_id,source_kind,source_id,amount,created_at) VALUES(?,?,?,?,?,?)').run(`${receipt}:merit`,uid,'WORLD_DEFENSE',runId,a.worldMerit,now());return{ok:true,overflow:add.overflow,message:`Dị Tượng đã được xử lý; nhận ${a.reward.lt} LT, ${a.reward.tuvi} Tu Vi${a.reward.cplt?`, ${a.reward.cplt} CPLT`:''}.`}}).value}
};
