import {createHash,randomUUID} from 'crypto';
import db from '../database/database';
import {ABILITIES,CombatMode,MODE_RULES,Strategy} from '../config/CombatCatalog';
import {statsService} from './StatsService';
import {contentResolver,runtimeKernel} from './RuntimeKernelService';
import {userRepository} from '../database/repositories/UserRepository';

type Fighter={id:string;ownerId?:string;name:string;side:number;hp:number;maxHp:number;qi:number;maxQi:number;atk:number;def:number;speed:number;strategy:Strategy;alive:boolean;cooldowns:Record<string,number>;guard:number};
export interface EnemyInput{id:string;name:string;hp:number;atk:number;def:number;speed?:number;qi?:number}
export interface StartCombatInput{mode:CombatMode;sourceId:string;sourceRunId:string;players:string[];enemies?:EnemyInput[];enemyDefinitionId?:string;opponents?:string[];seed?:string;strategy?:Strategy}
const hash=(x:string)=>createHash('sha256').update(x).digest('hex');
const stable=(seed:string,seq:number)=>parseInt(hash(`${seed}:${seq}`).slice(0,12),16)/0xffffffffffff;
const pack=(x:unknown)=>JSON.stringify(x);

function player(uid:string,side:number,strategy:Strategy):Fighter{const u=userRepository.get(uid),s=statsService.get(uid);if(!u||!s)throw new Error(`PLAYER_NOT_FOUND:${uid}`);const ratio=u.max_hp>0?Math.max(0,Math.min(1,u.hp/u.max_hp)):1,hp=Math.max(1,Math.round(s.hp*ratio));return{id:uid,ownerId:uid,name:u.name,side,hp,maxHp:s.hp,qi:Math.max(0,Math.min(u.mp,u.max_mp)),maxQi:u.max_mp,atk:s.atk,def:s.def,speed:s.speed,strategy,alive:hp>0,cooldowns:{},guard:0}}
function enemy(x:EnemyInput,side=2):Fighter{return{id:x.id,name:x.name,side,hp:x.hp,maxHp:x.hp,qi:x.qi??100,maxQi:x.qi??100,atk:x.atk,def:x.def,speed:x.speed??90,strategy:'CAN_BANG',alive:true,cooldowns:{},guard:0}}
function publicState(fs:Fighter[]){return fs.map(x=>({id:x.id,side:x.side,hp:x.hp,qi:x.qi,alive:x.alive,guard:x.guard,cooldowns:x.cooldowns}))}

export const combatEngine={
 start(input:StartCombatInput){
  const old=db.prepare('SELECT * FROM combat_encounters WHERE source_id=? AND source_run_id=?').get(input.sourceId,input.sourceRunId) as any;if(old)return{ok:true,replayed:true,encounterId:old.id,state:old.state};
  const rule=MODE_RULES[input.mode];if(!rule)throw new Error('COMBAT_MODE_NOT_AUTHORED');
  const ids=[...new Set([...(input.players||[]),...(input.opponents||[])])];if(!ids.length)throw new Error('EMPTY_ROSTER');
  const id=randomUUID(),leases:string[]=[];
  try{
   for(const uid of ids){const l=runtimeKernel.acquireLease(uid,'MUTATING_COMBAT_LEASE',id);if(!l.ok)throw new Error(l.message);leases.push(uid)}
   const strategy=input.strategy||'CAN_BANG',dynamic=input.enemyDefinitionId?contentResolver.pin(id,input.enemyDefinitionId,'monster'):null,dynamicEnemies:EnemyInput[]=dynamic?[{id:dynamic.id,name:dynamic.data.name,hp:Number(dynamic.data.hp),atk:Number(dynamic.data.atk),def:Number(dynamic.data.def),speed:Number(dynamic.data.speed||90)}]:[],fighters=[...input.players.map(x=>player(x,1,strategy)),...(input.opponents||[]).map(x=>player(x,2,strategy)),...(input.enemies||dynamicEnemies).map(x=>enemy(x))];
   if(!fighters.some(x=>x.side===2))throw new Error('MISSING_OPPOSITION');if(fighters.some(x=>![x.hp,x.maxHp,x.atk,x.def,x.speed].every(Number.isFinite)||x.hp<=0||x.atk<0||x.def<0))throw new Error('INVALID_COMBAT_DEFINITION');const seed=input.seed||hash(`${input.sourceId}:${input.sourceRunId}`),t=Date.now(),snapshot={fighters,resolverVersion:1,rewardOwner:rule.rewardOwner,strategy};
   db.transaction(()=>{db.prepare("INSERT INTO combat_encounters(id,world_epoch,mode,source_id,source_run_id,state,persistence,resolver_version,seed,snapshot_json,max_cycles,created_at,locked_at) VALUES(?,?,?,?,?,'LOCKED',?,?,?,?,?,?,?)").run(id,runtimeKernel.epoch(),input.mode,input.sourceId,input.sourceRunId,rule.persistence,1,seed,pack(snapshot),rule.maxCycles,t,t);const q=db.prepare('INSERT INTO combat_participants(encounter_id,entity_id,owner_id,side,kind,snapshot_json) VALUES(?,?,?,?,?,?)');for(const f of fighters)q.run(id,f.id,f.ownerId||null,f.side,f.ownerId?'PLAYER':'ENEMY',pack(f))})();
   return this.run(id);
  }catch(e){for(const uid of leases)runtimeKernel.releaseLease(uid,'MUTATING_COMBAT_LEASE',id);throw e}
 },
 run(id:string){const e=db.prepare('SELECT * FROM combat_encounters WHERE id=?').get(id) as any;if(!e)throw new Error('ENCOUNTER_NOT_FOUND');if(['SETTLED','VICTORY','DEFEAT','TIMEOUT'].includes(e.state))return{ok:true,replayed:true,encounterId:id,state:e.state,result:JSON.parse(e.result_json||'{}')};runtimeKernel.assertEpoch(e.world_epoch);const snapshot=JSON.parse(e.snapshot_json),fs:Fighter[]=snapshot.fighters,events:any[]=[];let seq=0,terminal='TIMEOUT';
  db.prepare("UPDATE combat_encounters SET state='RUNNING' WHERE id=? AND state='LOCKED'").run(id);
  for(let cycle=1;cycle<=e.max_cycles;cycle++){
   const order=fs.filter(x=>x.alive).sort((a,b)=>b.speed-a.speed||a.id.localeCompare(b.id));
   for(const actor of order){if(!actor.alive)continue;const allies=fs.filter(x=>x.alive&&x.side===actor.side),targets=fs.filter(x=>x.alive&&x.side!==actor.side);if(!targets.length)break;for(const k of Object.keys(actor.cooldowns))actor.cooldowns[k]=Math.max(0,actor.cooldowns[k]-1);
    const low=allies.sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp||a.id.localeCompare(b.id))[0];let ability=actor.strategy==='BAO_TOAN'&&low.hp/low.maxHp<.45&&actor.qi>=ABILITIES.mend.qiCost&&!(actor.cooldowns.mend>0)?ABILITIES.mend:actor.hp/actor.maxHp<.35&&actor.qi>=ABILITIES.guard.qiCost&&!(actor.cooldowns.guard>0)?ABILITIES.guard:actor.qi>=ABILITIES.heavy.qiCost&&!(actor.cooldowns.heavy>0)?ABILITIES.heavy:ABILITIES.basic;
    const target=ability.target==='ENEMY'?targets.sort((a,b)=>a.hp-b.hp||a.id.localeCompare(b.id))[0]:ability.target==='ALLY'?low:actor,inputHash=hash(pack(publicState(fs)));actor.qi=Math.max(0,actor.qi-ability.qiCost);if(ability.cooldown)actor.cooldowns[ability.id]=ability.cooldown;
    let delta:any={qi:-ability.qiCost};if(ability.kind==='DAMAGE'){const variance=.9+stable(e.seed,seq+1)*.2,raw=Math.max(1,Math.floor(actor.atk*ability.power*variance-target.def*.42)),amount=Math.max(0,Math.floor(raw*(1-target.guard)));target.guard=0;target.hp=Math.max(0,target.hp-amount);target.alive=target.hp>0;delta={...delta,damage:amount,targetHp:target.hp}}
    else if(ability.kind==='HEAL'){const amount=Math.min(target.maxHp-target.hp,Math.floor(actor.atk*ability.power));target.hp+=amount;delta={...delta,heal:amount,targetHp:target.hp}}
    else{actor.guard=Math.max(actor.guard,ability.power);delta={...delta,guard:actor.guard}}seq++;events.push({encounter_id:id,seq,cycle,actor_id:actor.id,target_id:target.id,event_type:ability.kind,action_id:ability.id,delta_json:pack(delta),input_hash:inputHash,output_hash:hash(pack(publicState(fs))),tags_json:'[]'});
   }
   const side1=fs.some(x=>x.alive&&x.side===1),side2=fs.some(x=>x.alive&&x.side===2);if(!side1||!side2){terminal=side1?'VICTORY':'DEFEAT';break}
  }
  const result={terminal,cycles:events.at(-1)?.cycle||0,events:events.length,participants:fs.map(x=>({id:x.id,side:x.side,hp:x.hp,maxHp:x.maxHp,alive:x.alive}))};db.transaction(()=>{const q=db.prepare('INSERT INTO combat_events(encounter_id,seq,cycle,actor_id,target_id,event_type,action_id,delta_json,input_hash,output_hash,tags_json) VALUES(@encounter_id,@seq,@cycle,@actor_id,@target_id,@event_type,@action_id,@delta_json,@input_hash,@output_hash,@tags_json)');for(const x of events)q.run(x);db.prepare('UPDATE combat_encounters SET state=?,result_json=? WHERE id=?').run(terminal,pack(result),id)})();return{ok:true,replayed:false,encounterId:id,state:terminal,result}
 },
 settle(id:string,sourceReceiptKey:string,settler:(result:any)=>unknown=()=>({})){const prior=db.prepare('SELECT * FROM combat_settlements WHERE encounter_id=? AND source_receipt_key=?').get(id,sourceReceiptKey) as any;if(prior)return{ok:true,replayed:true,terminal:prior.result,source:JSON.parse(prior.payload_json)};const e=db.prepare('SELECT * FROM combat_encounters WHERE id=?').get(id) as any;if(!e||!['VICTORY','DEFEAT','TIMEOUT','RETREAT','OBJECTIVE_COMPLETE'].includes(e.state))return{ok:false,message:'COMBAT_NOT_TERMINAL'};const rr=runtimeKernel.execute(sourceReceiptKey,'COMBAT',null,'SETTLE',()=>{const result=JSON.parse(e.result_json);const source=settler(result);if(e.persistence==='PERSISTENT')for(const p of result.participants.filter((x:any)=>x.side===1)){const u=userRepository.get(p.id);if(u)db.prepare('UPDATE users SET hp=MIN(max_hp,?) WHERE discord_id=?').run(p.hp,p.id)}db.prepare('INSERT INTO combat_settlements(encounter_id,source_receipt_key,result,payload_json,settled_at) VALUES(?,?,?,?,?)').run(id,sourceReceiptKey,result.terminal,pack(source),Date.now());db.prepare("UPDATE combat_encounters SET state='SETTLED',settled_at=? WHERE id=?").run(Date.now(),id);for(const p of result.participants)if(userRepository.get(p.id))runtimeKernel.releaseLease(p.id,'MUTATING_COMBAT_LEASE',id);runtimeKernel.emit('COMBAT_SETTLED',`combat:${id}`,{id,sourceReceiptKey,result:result.terminal});return{terminal:result.terminal,source}});return{ok:true,replayed:rr.replayed,...rr.value}},
 replay(id:string,detail:'SUMMARY'|'CYCLES'|'DETAIL'='SUMMARY'){const e=db.prepare('SELECT * FROM combat_encounters WHERE id=?').get(id) as any;if(!e)return null;const events=db.prepare('SELECT * FROM combat_events WHERE encounter_id=? ORDER BY seq').all(id) as any[];const result=JSON.parse(e.result_json||'{}');if(detail==='SUMMARY')return{id,mode:e.mode,state:e.state,result,eventCount:events.length};if(detail==='CYCLES')return{id,result,cycles:[...new Set(events.map(x=>x.cycle))].map(c=>({cycle:c,events:events.filter(x=>x.cycle===c).length}))};return{id,result,events}},
 audit(id:string){const events=db.prepare('SELECT * FROM combat_events WHERE encounter_id=? ORDER BY seq').all(id) as any[],errors:string[]=[];events.forEach((x,i)=>{if(x.seq!==i+1)errors.push(`seq gap ${i+1}`);if(Number(JSON.parse(x.delta_json).damage||0)<0)errors.push(`negative damage ${x.seq}`)});const settlements=(db.prepare('SELECT COUNT(*) n FROM combat_settlements WHERE encounter_id=?').get(id) as any).n;if(settlements>1)errors.push('double settlement');return errors}
};
