import {RECIPES,ITEMS,realmOf,itemName,itemEmoji} from '../config/GameCatalog';import {userRepository} from '../database/repositories/UserRepository';import {inventoryRepository} from '../database/repositories/InventoryRepository';import db from '../database/database';import {dutyService} from './DutyService';import {rareFireService} from './RareFireService';import {applyFireQuality,resolveRareFire} from './RareFireResolver';import {storageService} from './StorageService';import {itemInstanceService} from './ItemInstanceService';import {qilingRuntime} from './RuntimeSystemsService';
const level=(exp:number)=>exp>=120?6:exp>=60?5:exp>=25?4:exp>=10?3:exp>=3?2:1;export const PROFESSION_NAMES=['','Học Đồ','Nhập Môn','Tinh Thục','Đại Thành','Tông Sư','Đạo Sư'];
export const craftingService={
 mastery(uid:string,kind:string){return(db.prepare('SELECT * FROM craft_mastery WHERE user_id=? AND kind=?').get(uid,kind) as any)||{exp:0,level:1}},
 chance(uid:string,rid:string){const r=RECIPES.find(x=>x.id===rid),u=userRepository.get(uid);if(!r||!u)return 0;const m=this.mastery(uid,r.kind);return Math.min(.98,.68+m.level*.05+Math.max(0,realmOf(u.level).rank-r.minRealm)*.02)},
 craft(uid:string,rid:string,fireId?:string,roll=Math.random()){
  const u=userRepository.get(uid),r=RECIPES.find(x=>x.id===rid);if(!u)return{ok:false,message:'Đạo hữu chưa lập đạo hồ.'};if(!r)return{ok:false,message:'Không tìm thấy bí phương.'};if(r.id.startsWith('storage_bag_'))return storageService.craft(uid,r.id);const m=this.mastery(uid,r.kind),required=Math.min(6,r.minRealm+1);if(m.level<required)return{ok:false,message:`Bí phương yêu cầu ${PROFESSION_NAMES[required]} cấp ${required}; hiện tại ${PROFESSION_NAMES[m.level]} cấp ${m.level}.`};if(realmOf(u.level).rank<r.minRealm)return{ok:false,message:'Cảnh giới chưa đủ.'};if(u.coin_ha_pham<r.lt)return{ok:false,message:'Linh Thạch không đủ.'};for(const[x,q]of r.ingredients)if(inventoryRepository.quantity(uid,x)<q)return{ok:false,message:`Thiếu ${itemName(x)} (${inventoryRepository.quantity(uid,x)}/${q}).`};
  let mastery:'so_dan'|'thuan_hoa'|'tri_tinh'|'hop_dung'='so_dan';if(fireId){if(!r.fire)return{ok:false,message:'Bí phương không hỗ trợ Dị Hỏa.'};const o=rareFireService.get(uid,fireId);if(!o||!o.placed_at)return{ok:false,message:'Dị Hỏa chưa được sở hữu/an trí.'};mastery=o.mastery}const fire=resolveRareFire(fireId,r.fire,mastery);if(!fire.allowed)return{ok:false,message:`Chủ Hỏa không tương thích: ${fire.reason}`};const chance=this.chance(uid,rid),success=roll<chance,out=ITEMS[r.output[0]],baseScore=Math.min(89,60+Math.max(0,realmOf(u.level).rank-r.minRealm)*3),quality=applyFireQuality(baseScore,fire);let overflow=false,spirit='';
  db.transaction(()=>{for(const[x,q]of r.ingredients)inventoryRepository.remove(uid,x,q);db.prepare('UPDATE users SET coin_ha_pham=coin_ha_pham-? WHERE discord_id=?').run(r.lt,uid);db.prepare('INSERT INTO craft_mastery(user_id,kind,exp,level) VALUES(?,?,1,1) ON CONFLICT(user_id,kind) DO UPDATE SET exp=exp+1').run(uid,r.kind);const e=(db.prepare('SELECT exp FROM craft_mastery WHERE user_id=? AND kind=?').get(uid,r.kind) as any).exp;db.prepare('UPDATE craft_mastery SET level=? WHERE user_id=? AND kind=?').run(level(e),uid,r.kind);if(!success)return;const t=Date.now(),p=db.prepare('INSERT INTO rare_fire_process_log(user_id,recipe_id,fire_id,compatibility,base_score,final_score,quality_band,created_at) VALUES(?,?,?,?,?,?,?,?)').run(uid,r.id,fireId||null,fire.compatibility,baseScore,quality.score,quality.band,Math.floor(t/1000)),pid=Number(p.lastInsertRowid);if(['weapon','armor'].includes(out.type)){const x=itemInstanceService.create(uid,r.output[0],out.type,{source:'CRAFT',recipeId:r.id,processId:pid,fireId:fireId||null},{quality:out.rarity,binding:'UNBOUND'});overflow=x.location==='TEMPORARY';if(out.type==='weapon'){const c=Math.min(.35,.02+r.minRealm*.025+(fireId?.04:0)),q=qilingRuntime.seed(uid,x.instance_id,c);if(q.message.includes('đã sinh'))spirit=' Vật Mang đã sinh Linh Cơ.'}}else overflow=inventoryRepository.add(uid,r.output[0],r.output[1]).overflow>0;db.prepare('INSERT INTO crafted_outputs(process_id,user_id,item_id,quantity,quality_band,fire_id,created_at) VALUES(?,?,?,?,?,?,?)').run(pid,uid,r.output[0],r.output[1],quality.band,fireId||null,Math.floor(t/1000))})();dutyService.inc(uid,'craft');return success?{ok:true,message:`${itemEmoji(r.output[0])} Thu được ${itemName(r.output[0])} ×${r.output[1]}.${overflow?' Thành phẩm vào Tạm Nang.':''}${spirit}`}:{ok:true,message:`Chế tác thất bại (${Math.round(chance*100)}%); nguyên liệu đã tiêu hao, nghề vẫn nhận EXP.`};
 },
 craftMany(uid:string,rid:string,count:number){if(![1,5,10].includes(count))return{ok:false,message:'Chỉ hỗ trợ ×1, ×5 hoặc ×10.'};const r=RECIPES.find(x=>x.id===rid),u=userRepository.get(uid);if(!r||!u)return{ok:false,message:'Không tìm thấy bí phương.'};if(u.coin_ha_pham<r.lt*count)return{ok:false,message:`Thiếu LT cho ${count} lượt.`};for(const[x,q]of r.ingredients)if(inventoryRepository.quantity(uid,x)<q*count)return{ok:false,message:`Thiếu ${itemName(x)}: ${inventoryRepository.quantity(uid,x)}/${q*count}.`};let success=0,fail=0;for(let i=0;i<count;i++){const z=this.craft(uid,rid);z.message.includes('thất bại')?fail++:success++}return{ok:true,message:`Hoàn tất ${count} lượt: ${success} thành / ${fail} bại.`}}
};
