import {randomUUID} from 'crypto';
import db from '../database/database';
import {SECRET_REALMS,realmOf} from '../config/GameCatalog';
import {userRepository} from '../database/repositories/UserRepository';
import {inventoryRepository} from '../database/repositories/InventoryRepository';
import {combatEngine} from './CombatEngineService';
import {runtimeKernel} from './RuntimeKernelService';
import {rewardNotificationService} from './RewardNotificationService';

const now=()=>Date.now();
export const dungeonPartyService={
 current(uid:string){return db.prepare('SELECT p.* FROM party_lobbies p JOIN party_members m ON m.party_id=p.id WHERE m.user_id=?').get(uid) as any},
 members(partyId:string){return db.prepare('SELECT m.*,u.name,u.level,u.hp,u.max_hp FROM party_members m JOIN users u ON u.discord_id=m.user_id WHERE m.party_id=? ORDER BY m.joined_at').all(partyId) as any[]},
 create(uid:string,realmId:string){const realm=SECRET_REALMS.find(x=>x.id===realmId),u=userRepository.get(uid);if(!realm||!u||realmOf(u.level).rank<realm.minRealm)return{ok:false,message:'Không đủ điều kiện lập đội cho Bí Cảnh này.'};if(this.current(uid))return{ok:false,message:'Đạo hữu đang ở trong một tổ đội.'};const id=randomUUID();db.transaction(()=>{db.prepare('INSERT INTO party_lobbies(id,leader_id,realm_id,status,created_at,updated_at) VALUES(?,?,?,\'FORMING\',?,?)').run(id,uid,realmId,now(),now());db.prepare('INSERT INTO party_members(party_id,user_id,ready,joined_at) VALUES(?,?,1,?)').run(id,uid,now())})();return{ok:true,id,message:'Đã lập tổ đội.'}},
 invite(leaderId:string,targetId:string){const p=this.current(leaderId);if(!p||p.leader_id!==leaderId||p.status!=='FORMING')return{ok:false,message:'Chỉ đội trưởng của đội đang chuẩn bị mới được mời.'};if(!userRepository.get(targetId)||this.current(targetId)||this.members(p.id).length>=4)return{ok:false,message:'Người được mời không hợp lệ hoặc đội đã đầy.'};db.prepare('INSERT INTO party_invites(party_id,target_id,inviter_id,expires_at) VALUES(?,?,?,?) ON CONFLICT(party_id,target_id) DO UPDATE SET inviter_id=excluded.inviter_id,expires_at=excluded.expires_at').run(p.id,targetId,leaderId,now()+10*60_000);return{ok:true,message:'Lời mời có hiệu lực trong 10 phút.'}},
 accept(uid:string,partyId:string){const inv=db.prepare('SELECT * FROM party_invites WHERE party_id=? AND target_id=? AND expires_at>?').get(partyId,uid,now()) as any,p=db.prepare("SELECT * FROM party_lobbies WHERE id=? AND status='FORMING'").get(partyId) as any;if(!inv||!p||this.current(uid)||this.members(partyId).length>=4)return{ok:false,message:'Lời mời không còn hợp lệ.'};const realm=SECRET_REALMS.find(x=>x.id===p.realm_id)!,u=userRepository.get(uid)!;if(realmOf(u.level).rank<realm.minRealm)return{ok:false,message:'Cảnh giới chưa đạt điều kiện của Bí Cảnh.'};db.transaction(()=>{db.prepare('INSERT INTO party_members(party_id,user_id,ready,joined_at) VALUES(?,?,0,?)').run(partyId,uid,now());db.prepare('DELETE FROM party_invites WHERE party_id=? AND target_id=?').run(partyId,uid)})();return{ok:true,message:'Đã vào đội; hãy xác nhận sẵn sàng.'}},
 join(uid:string,partyId:string){const p=db.prepare("SELECT * FROM party_lobbies WHERE id=? AND status='FORMING'").get(partyId) as any;if(!p||this.current(uid)||this.members(partyId).length>=4)return{ok:false,message:'Không thể gia nhập đội.'};const realm=SECRET_REALMS.find(x=>x.id===p.realm_id),u=userRepository.get(uid);if(!realm||!u||realmOf(u.level).rank<realm.minRealm)return{ok:false,message:'Cảnh giới chưa đủ.'};db.prepare('INSERT INTO party_members(party_id,user_id,ready,joined_at) VALUES(?,?,0,?)').run(partyId,uid,now());return{ok:true,message:'Đã trực tiếp gia nhập đội.'}},
 kick(leaderId:string,targetId:string){const p=this.current(leaderId);if(!p||p.leader_id!==leaderId||p.status!=='FORMING'||targetId===leaderId)return{ok:false,message:'Không thể loại thành viên này.'};const r=db.prepare('DELETE FROM party_members WHERE party_id=? AND user_id=?').run(p.id,targetId);return{ok:!!r.changes,message:r.changes?'Đã mời thành viên rời đội.':'Thành viên không còn trong đội.'}},
 transfer(leaderId:string,targetId:string){const p=this.current(leaderId);if(!p||p.leader_id!==leaderId||p.status!=='FORMING'||!this.members(p.id).some(x=>x.user_id===targetId))return{ok:false,message:'Không thể chuyển đội trưởng.'};db.transaction(()=>{db.prepare('UPDATE party_lobbies SET leader_id=?,updated_at=? WHERE id=?').run(targetId,now(),p.id);db.prepare('UPDATE party_members SET ready=0 WHERE party_id=?').run(p.id);db.prepare('UPDATE party_members SET ready=1 WHERE party_id=? AND user_id=?').run(p.id,targetId)})();return{ok:true,message:'Đã chuyển quyền đội trưởng; toàn đội cần xác nhận lại.'}},
 ready(uid:string){const p=this.current(uid);if(!p||p.status!=='FORMING')return{ok:false,message:'Đội không ở trạng thái chuẩn bị.'};db.prepare('UPDATE party_members SET ready=CASE ready WHEN 1 THEN 0 ELSE 1 END WHERE party_id=? AND user_id=?').run(p.id,uid);return{ok:true,message:'Đã đổi trạng thái sẵn sàng.'}},
 changeRealm(leaderId:string,realmId:string){const p=this.current(leaderId),realm=SECRET_REALMS.find(x=>x.id===realmId);if(!p||p.leader_id!==leaderId||p.status!=='FORMING'||!realm)return{ok:false,message:'Không thể đổi Bí Cảnh.'};if(this.members(p.id).some(x=>realmOf(x.level).rank<realm.minRealm))return{ok:false,message:'Có thành viên không đủ cảnh giới; Bí Cảnh chưa được đổi.'};db.transaction(()=>{db.prepare('UPDATE party_lobbies SET realm_id=?,updated_at=? WHERE id=?').run(realmId,now(),p.id);db.prepare('UPDATE party_members SET ready=CASE WHEN user_id=? THEN 1 ELSE 0 END WHERE party_id=?').run(leaderId,p.id)})();return{ok:true,message:'Đã đổi Bí Cảnh; thành viên cần sẵn sàng lại.'}},
 start(leaderId:string){const p=this.current(leaderId);if(!p||p.leader_id!==leaderId||p.status!=='FORMING')return{ok:false,message:'Không thể bắt đầu.'};const members=this.members(p.id);if(!members.length||members.some(x=>!x.ready))return{ok:false,message:'Còn thành viên chưa sẵn sàng.'};const id=randomUUID(),roster=members.map(x=>x.user_id);db.transaction(()=>{db.prepare("UPDATE party_lobbies SET status='RUNNING',updated_at=? WHERE id=?").run(now(),p.id);db.prepare("INSERT INTO dungeon_runs(id,party_id,realm_id,state,current_room,roster_json,leader_id,created_at,updated_at) VALUES(?,?,?,'ROUTE_CHOICE',0,?,?,?,?)").run(id,p.id,p.realm_id,JSON.stringify(roster),leaderId,now(),now())})();return{ok:true,runId:id,message:'Đội hình đã khóa; đội trưởng chọn hướng đi.'}},
 view(uid:string){const p=this.current(uid);if(!p)return null;const run=db.prepare('SELECT * FROM dungeon_runs WHERE party_id=? ORDER BY created_at DESC LIMIT 1').get(p.id) as any;return{party:p,members:this.members(p.id),run:run?{...run,route:JSON.parse(run.route_json)}:null,controls:p.leader_id===uid}},
  chooseRoute(leaderId:string,choice:'THAN_TRONG'|'TRUC_TIEN'|'THAM_SAT'){const p=this.current(leaderId),run=p&&db.prepare("SELECT * FROM dungeon_runs WHERE party_id=? AND state='ROUTE_CHOICE'").get(p.id) as any;if(!p||!run||run.leader_id!==leaderId)return{ok:false,message:'Chỉ đội trưởng đang nắm quyền chọn đường.'};const room=run.current_room+1,realm=SECRET_REALMS.find(x=>x.id===run.realm_id)!,players=JSON.parse(run.roster_json) as string[],scale=choice==='THAN_TRONG'?.82:choice==='THAM_SAT'?1.25:1;const fight=combatEngine.start({mode:'DUNGEON',sourceId:`dungeon:${run.id}`,sourceRunId:`room:${room}`,players,enemies:[{id:`${run.realm_id}:room:${room}`,name:`Thủ Vực · ${realm.name}`,hp:Math.floor(realm.power*scale),atk:Math.max(10,Math.floor(Math.sqrt(realm.power)*scale)),def:Math.max(5,Math.floor(Math.sqrt(realm.power)*.55)),speed:90+room}],seed:`${run.id}:${room}:${choice}`});db.transaction(()=>{db.prepare('INSERT INTO dungeon_room_receipts(run_id,room_no,choice_id,encounter_id,status,created_at) VALUES(?,?,?,?,\'COMBAT_TERMINAL\',?)').run(run.id,room,choice,fight.encounterId,now());db.prepare('UPDATE dungeon_runs SET state=\'COMBAT_TERMINAL\',current_room=?,route_json=json_insert(route_json,\'$[#]\',?),lock_version=lock_version+1,updated_at=? WHERE id=?').run(room,choice,now(),run.id)})();return{ok:true,runId:run.id,encounterId:fight.encounterId,result:'result' in fight?fight.result:combatEngine.replay(fight.encounterId),message:'Cả đội đã tự động giao chiến; chiến báo đã ghi nhận.'}},
 settleRoom(leaderId:string){const p=this.current(leaderId),run=p&&db.prepare("SELECT * FROM dungeon_runs WHERE party_id=? AND state='COMBAT_TERMINAL'").get(p.id) as any;if(!p||!run||run.leader_id!==leaderId)return{ok:false,message:'Không có gian Bí Cảnh chờ quyết toán.'};const room=db.prepare('SELECT * FROM dungeon_room_receipts WHERE run_id=? AND room_no=?').get(run.id,run.current_room) as any;const settled=combatEngine.settle(room.encounter_id,`dungeon:${run.id}:room:${run.current_room}`);const won=(settled as any).terminal==='VICTORY',complete=won&&run.current_room>=3,realm=SECRET_REALMS.find(x=>x.id===run.realm_id)!;db.transaction(()=>{db.prepare('UPDATE dungeon_room_receipts SET status=?,result_json=? WHERE run_id=? AND room_no=?').run(won?'CLEARED':'FAILED',JSON.stringify(settled),run.id,run.current_room);db.prepare('UPDATE dungeon_runs SET state=?,updated_at=?,settled_at=? WHERE id=?').run(!won?'FAILED':complete?'SETTLED':'ROUTE_CHOICE',now(),!won||complete?now():null,run.id);if(!won||complete)db.prepare("UPDATE party_lobbies SET status='COMPLETED',updated_at=? WHERE id=?").run(now(),p.id);if(complete)for(const uid of JSON.parse(run.roster_json) as string[]){db.prepare('INSERT INTO secret_realm_log(user_id,realm_id,last_entered,clears) VALUES(?,?,?,1) ON CONFLICT(user_id,realm_id) DO UPDATE SET last_entered=excluded.last_entered,clears=clears+1').run(uid,run.realm_id,now());db.prepare('UPDATE users SET tu_vi=tu_vi+? WHERE discord_id=?').run(realm.tuvi,uid);rewardNotificationService.push(uid,`DUNGEON:${run.id}`,`Tổ đội đã hoàn tất ${realm.name}; nhận ${realm.tuvi} Tu Vi.`)}})();return{ok:true,complete,won,message:won?(complete?'Bí Cảnh hoàn tất; thưởng nguồn Bí Cảnh đã quyết toán.':'Đã qua gian này; đội trưởng có thể chọn đường tiếp.'):'Tổ đội thất bại và rời Bí Cảnh.'}},
 healAtCheckpoint(actorId:string,targetIds:string[]){const p=this.current(actorId),run=p&&db.prepare("SELECT * FROM dungeon_runs WHERE party_id=? AND state='ROUTE_CHOICE'").get(p.id) as any;if(!p||!run)return{ok:false,message:'Chỉ được hồi phục tại điểm an toàn.'};const valid=new Set(this.members(p.id).map(x=>x.user_id)),targets=[...new Set(targetIds)].filter(x=>valid.has(x)&&userRepository.get(x)!.hp<userRepository.get(x)!.max_hp);if(!targets.length)return{ok:false,message:'Không có mục tiêu cần hồi phục.'};if(inventoryRepository.quantity(actorId,'pill_0')<targets.length)return{ok:false,message:`Cần ${targets.length} viên đan HP; mỗi mục tiêu dùng một liều.`};db.transaction(()=>{inventoryRepository.remove(actorId,'pill_0',targets.length);for(const uid of targets)db.prepare('UPDATE users SET hp=max_hp WHERE discord_id=?').run(uid)})();return{ok:true,message:`Đã dùng ${targets.length} viên, hồi đầy HP cho ${targets.length} thành viên.`}}
};
