import db from '../database/database';import {ITEMS,itemByNameOrId,itemName,SHOP_OFFERS,CPLT_OFFERS} from '../config/GameCatalog';import {inventoryRepository} from '../database/repositories/InventoryRepository';import {userRepository} from '../database/repositories/UserRepository';
export interface MarketListing{id:number;seller_id:string;item_id:string;quantity:number;price:number;status:string;created_at:number;expires_at:number;buyer_id?:string;name?:string;emoji?:string;seller_name?:string}
function now(){return Date.now()}
export const marketService={
 sweepExpired(){const rows=db.prepare("SELECT * FROM market_listings WHERE status='active' AND expires_at<=?").all(now()) as MarketListing[];if(!rows.length)return;db.transaction(()=>{for(const r of rows){inventoryRepository.add(r.seller_id,r.item_id,r.quantity);db.prepare("UPDATE market_listings SET status='expired' WHERE id=?").run(r.id)}})()},
 listings(limit=8){this.sweepExpired();return db.prepare(`SELECT m.*,i.name,i.emoji,u.name seller_name FROM market_listings m JOIN items i ON i.id=m.item_id JOIN users u ON u.discord_id=m.seller_id WHERE m.status='active' ORDER BY m.created_at DESC LIMIT ?`).all(limit) as MarketListing[]},
 create(uid:string,itemInput:string,quantity:number,price:number){this.sweepExpired();const item=itemByNameOrId(itemInput);if(!item)return{ok:false,message:'Không tìm thấy vật phẩm theo tên hoặc mã đã nhập.'};if(!item.tradable)return{ok:false,message:'Vật phẩm này đã bị khóa, không thể đưa lên Kim Vân Đài.'};if(quantity<1||quantity>999)return{ok:false,message:'Số lượng phải từ 1 đến 999.'};if(price<1)return{ok:false,message:'Giá bán phải lớn hơn 0 Linh Thạch.'};if(inventoryRepository.equipped(uid,item.id))return{ok:false,message:'Hãy tháo trang bị trước khi đưa lên Kim Vân Đài.'};if(inventoryRepository.quantity(uid,item.id)<quantity)return{ok:false,message:`Linh nang không đủ **${item.name}**.`};const fee=Math.max(1,Math.floor(price*.02));const u=userRepository.get(uid)!;if(u.coin_ha_pham<fee)return{ok:false,message:`Cần **${fee} LT** làm phí đăng bán.`};db.transaction(()=>{inventoryRepository.remove(uid,item.id,quantity);db.prepare('UPDATE users SET coin_ha_pham=coin_ha_pham-? WHERE discord_id=?').run(fee,uid);db.prepare(`INSERT INTO market_listings(seller_id,item_id,quantity,price,created_at,expires_at) VALUES(?,?,?,?,?,?)`).run(uid,item.id,quantity,price,now(),now()+48*3600_000)})();return{ok:true,message:`🏮 Đã đưa **${item.name} ×${quantity}** lên Kim Vân Đài với giá **${price} LT**. Phí đăng bán: **${fee} LT**.`}},
 buy(uid:string,id:number){this.sweepExpired();const l=db.prepare("SELECT * FROM market_listings WHERE id=? AND status='active'").get(id) as MarketListing|undefined;if(!l)return{ok:false,message:'Giao dịch này không còn tồn tại.'};if(l.seller_id===uid)return{ok:false,message:'Không thể tự mua vật phẩm của chính mình.'};const buyer=userRepository.get(uid);if(!buyer||buyer.coin_ha_pham<l.price)return{ok:false,message:'Linh Thạch không đủ để hoàn thành giao dịch.'};const tax=Math.max(1,Math.floor(l.price*.05)),sellerGain=l.price-tax;db.transaction(()=>{db.prepare('UPDATE users SET coin_ha_pham=coin_ha_pham-? WHERE discord_id=?').run(l.price,uid);db.prepare('UPDATE users SET coin_ha_pham=coin_ha_pham+? WHERE discord_id=?').run(sellerGain,l.seller_id);inventoryRepository.add(uid,l.item_id,l.quantity);db.prepare("UPDATE market_listings SET status='sold',buyer_id=? WHERE id=?").run(uid,id)})();return{ok:true,message:`🤝 Giao dịch hoàn thành. Nhận **${itemName(l.item_id)} ×${l.quantity}** với giá **${l.price} LT**.`}},
 cancel(uid:string,id:number){const l=db.prepare("SELECT * FROM market_listings WHERE id=? AND status='active'").get(id) as MarketListing|undefined;if(!l||l.seller_id!==uid)return{ok:false,message:'Không tìm thấy giao dịch đang bán của đạo hữu.'};db.transaction(()=>{inventoryRepository.add(uid,l.item_id,l.quantity);db.prepare("UPDATE market_listings SET status='cancelled' WHERE id=?").run(id)})();return{ok:true,message:`Đã thu hồi **${itemName(l.item_id)} ×${l.quantity}** về linh nang.`}},
 buyNpc(uid:string,itemId:string){const offer=SHOP_OFFERS.find(x=>x.item===itemId);if(!offer)return{ok:false,message:'Nhất Phẩm Các hiện không bày bán vật phẩm này.'};const u=userRepository.get(uid)!;if(u.coin_ha_pham<offer.price)return{ok:false,message:'Linh Thạch không đủ.'};db.transaction(()=>{db.prepare('UPDATE users SET coin_ha_pham=coin_ha_pham-? WHERE discord_id=?').run(offer.price,uid);inventoryRepository.add(uid,itemId,1)})();return{ok:true,message:`🏮 Đã mua **${ITEMS[itemId].name}** với giá **${offer.price} LT**.`}},
 buyCplt(uid:string,itemId:string){const offer=CPLT_OFFERS.find(x=>x.item===itemId);if(!offer)return{ok:false,message:'Không có vật đổi này.'};const u=userRepository.get(uid)!;if(u.knb<offer.price)return{ok:false,message:'Cực Phẩm Linh Thạch không đủ.'};db.transaction(()=>{db.prepare('UPDATE users SET knb=knb-? WHERE discord_id=?').run(offer.price,uid);inventoryRepository.add(uid,itemId,1)})();return{ok:true,message:`🔷 Đã đổi **${ITEMS[itemId].name}** với **${offer.price} CPLT**.`}},
 exchangeToken(uid:string,token:'tranhai_lenh'|'xichduc_lenh'){const reward=token==='tranhai_lenh'?'pill_1':'beast_2';if(inventoryRepository.quantity(uid,token)<3)return{ok:false,message:`Cần **3 ${itemName(token)}** để đổi vật.`};db.transaction(()=>{inventoryRepository.remove(uid,token,3);inventoryRepository.add(uid,reward,1)})();return{ok:true,message:`Đã dùng **3 ${itemName(token)}** đổi lấy **${itemName(reward)}**.`}}
};
