import db from '../database/database';import {createHash,randomBytes,randomUUID} from 'crypto';import {ownerControlService} from './OwnerControlService';import {ownerAdvancedService} from './OwnerAdvancedService';
const hash=(x:string)=>createHash('sha256').update(x).digest('hex');const epoch=()=>Number((db.prepare("SELECT value FROM world_meta WHERE key='world_epoch'").get() as any)?.value||1);
function create(owner:string,target:string,action:string,payload:any,before:any){const id=randomUUID(),nonce=randomBytes(8).toString('hex'),expires=Date.now()+10*60_000;payload.worldEpoch=epoch();db.prepare("INSERT INTO owner_mutations(id,owner_id,target_id,action,payload_json,before_json,nonce_hash,expires_at,status,created_at) VALUES(?,?,?,?,?,?,?,?,'PENDING',?)").run(id,owner,target,action,JSON.stringify(payload),JSON.stringify(before),hash(nonce),expires,Date.now());return{ok:true,id,nonce,expires,action,before,payload,message:'High-risk preview đã tạo; cần nonce xác nhận lần hai.'}}
export const ownerApprovalService={
 previewCplt(owner:string,target:string,operation:'GRANT'|'REVOKE'|'SET',amount:number){const u=db.prepare('SELECT discord_id,name,knb,updated_at FROM users WHERE discord_id=?').get(target) as any;if(!u||!Number.isSafeInteger(amount)||amount<0)return{ok:false,message:'Target hoặc CPLT không hợp lệ.'};const after=operation==='GRANT'?u.knb+amount:operation==='REVOKE'?u.knb-amount:amount;if(after<0)return{ok:false,message:'REJECT_INSUFFICIENT.'};return create(owner,target,`CPLT_${operation}`,{operation,amount,expected:u.knb,after},{...u})},
 previewContent(owner:string,id:string,version:number,operation:'PUBLISH'|'RETIRE'){const d=db.prepare('SELECT definition_id,kind,version,status,data_json FROM content_definitions WHERE definition_id=? AND version=?').get(id,version) as any;if(!d)return{ok:false,message:'Không tìm thấy content version.'};if(operation==='PUBLISH'&&d.status!=='DRAFT'||operation==='RETIRE'&&d.status!=='PUBLISHED')return{ok:false,message:'Content state không hợp lệ cho thao tác.'};return create(owner,id,`CONTENT_${operation}`,{operation,version,expectedStatus:d.status},{name:id,...d})},
 previewRepair(owner:string,target:string,field:'hp'|'stamina'|'tu_vi',value:number,reason:string,provenance:string,key:string){if(!['hp','stamina','tu_vi'].includes(field)||!Number.isSafeInteger(value)||value<0||reason.length<3||provenance.length<3||key.length<8)return{ok:false,message:'Repair payload không hợp lệ.'};const u=db.prepare(`SELECT discord_id,name,${field} value,updated_at FROM users WHERE discord_id=?`).get(target) as any;if(!u)return{ok:false,message:'Không tìm thấy người chơi.'};if(db.prepare('SELECT 1 FROM system_repairs WHERE idempotency_key=?').get(key))return{ok:false,message:'Idempotency key đã được dùng.'};return create(owner,target,'SYSTEM_REPAIR',{field,value,reason,provenance,key,expected:u.value},{...u})},
 confirm(owner:string,id:string,nonce:string){const m=db.prepare("SELECT * FROM owner_mutations WHERE id=? AND owner_id=? AND status='PENDING'").get(id,owner) as any;if(!m||m.expires_at<Date.now()||m.nonce_hash!==hash(nonce))return{ok:false,message:'Nonce sai, đã dùng hoặc hết hạn.'};const p=JSON.parse(m.payload_json);if(p.worldEpoch!==epoch())return{ok:false,message:'STALE_PREVIEW: world_epoch đã thay đổi.'};let r:any;if(m.action.startsWith('CPLT_')){const u=db.prepare('SELECT knb FROM users WHERE discord_id=?').get(m.target_id) as any;if(!u||u.knb!==p.expected)return{ok:false,message:'STALE_PREVIEW: số dư CPLT đã thay đổi.'};r=ownerControlService.adjustCurrency(owner,m.target_id,'CPLT',p.operation,p.amount,true)}else if(m.action.startsWith('CONTENT_')){const d=db.prepare('SELECT status FROM content_definitions WHERE definition_id=? AND version=?').get(m.target_id,p.version) as any;if(!d||d.status!==p.expectedStatus)return{ok:false,message:'STALE_PREVIEW: content state đã thay đổi.'};r=p.operation==='PUBLISH'?ownerAdvancedService.publishContent(owner,m.target_id,p.version):ownerAdvancedService.retireContent(owner,m.target_id,p.version)}else if(m.action==='SYSTEM_REPAIR'){const u=db.prepare(`SELECT ${p.field} value FROM users WHERE discord_id=?`).get(m.target_id) as any;if(!u||u.value!==p.expected)return{ok:false,message:'STALE_PREVIEW: target state đã thay đổi.'};r=ownerAdvancedService.repairScalar(owner,m.target_id,p.field,p.value,p.reason,p.provenance,p.key)}else return{ok:false,message:'Action high-risk không được hỗ trợ.'};if(!r.ok)return r;db.prepare("UPDATE owner_mutations SET status='APPLIED',nonce_hash='',applied_at=? WHERE id=?").run(Date.now(),id);return{ok:true,message:r.message}},
 rejectExpired(){return db.prepare("UPDATE owner_mutations SET status='EXPIRED',nonce_hash='' WHERE status='PENDING' AND expires_at<=?").run(Date.now()).changes}
};
