import {randomUUID} from 'crypto';
import db from '../database/database';
import {runtimeKernel} from './RuntimeKernelService';
import {userRepository} from '../database/repositories/UserRepository';
import {npcById} from '../config/NpcCatalog';

const now=()=>Date.now();
const pair=(a:string,b:string)=>a<b?[a,b]:[b,a];
function cooldown(uid:string,kind:string){return Number((db.prepare('SELECT available_at FROM relationship_cooldowns WHERE user_id=? AND kind=?').get(uid,kind) as any)?.available_at||0)}
function activeBond(uid:string){return db.prepare("SELECT * FROM partner_bonds WHERE status='ACTIVE' AND (player_a=? OR player_b=?)").get(uid,uid) as any}
function bondStage(id:string){const rows=db.prepare('SELECT domain,choice_shared FROM bond_milestones WHERE bond_id=?').all(id) as any[],domains=new Set(rows.map(x=>x.domain));if(rows.some(x=>x.domain==='SONG_HANH_CO_DUYEN'))return'TUONG_CHIEU';if(rows.length>=6&&domains.size>=4&&rows.some(x=>x.choice_shared))return'TUONG_TRI';if(domains.size>=3)return'SONG_HANH';return'DONG_DAO'}

export const relationshipRuntime={
 pendingInvite(uid:string){return db.prepare("SELECT * FROM partner_invites WHERE status IN ('INVITE_PENDING','ACCEPTED_PENDING_CONFIRM') AND expires_at>? AND (sender_id=? OR receiver_id=?) ORDER BY created_at DESC LIMIT 1").get(now(),uid,uid) as any},
 pendingDual(uid:string){return db.prepare("SELECT s.*,b.player_a,b.player_b FROM dual_cultivation_sessions s JOIN partner_bonds b ON b.id=s.bond_id WHERE b.status='ACTIVE' AND (b.player_a=? OR b.player_b=?) AND s.state='PROPOSED' ORDER BY s.created_at DESC LIMIT 1").get(uid,uid) as any},
 recordShared(a:string,b:string,domain:string,activityId:string,receiptKey:string,sharedChoice=false){const [x,y]=pair(a,b);return runtimeKernel.execute(receiptKey,'RELATIONSHIP',x,'SHARED_ACTIVITY',()=>{db.prepare('INSERT INTO shared_activity_receipts(receipt_key,player_a,player_b,domain,activity_id,created_at) VALUES(?,?,?,?,?,?)').run(receiptKey,x,y,domain,activityId,now());const bond=activeBond(x);if(bond&&(bond.player_a===y||bond.player_b===y))db.prepare('INSERT OR IGNORE INTO bond_milestones(bond_id,domain,activity_id,choice_shared,created_at) VALUES(?,?,?,?,?)').run(bond.id,domain,activityId,sharedChoice?1:0,now());return{ok:true}}).value},
 proposePartner(sender:string,receiver:string){if(sender===receiver||!userRepository.get(sender)||!userRepository.get(receiver))return{ok:false,message:'Lời mời không hợp lệ.'};if(activeBond(sender)||activeBond(receiver)||cooldown(sender,'DAO_LU')>now()||cooldown(receiver,'DAO_LU')>now())return{ok:false,message:'Một bên đang có Đạo Lữ hoặc còn trong 24 giờ hậu Giải Ước.'};const [a,b]=pair(sender,receiver);if(!db.prepare('SELECT 1 FROM shared_activity_receipts WHERE player_a=? AND player_b=?').get(a,b))return{ok:false,message:'Cần ít nhất một shared activity receipt hợp lệ.'};const id=randomUUID();db.prepare("INSERT INTO partner_invites(id,sender_id,receiver_id,status,expires_at,created_at) VALUES(?,?,?,'INVITE_PENDING',?,?)").run(id,sender,receiver,now()+48*3600_000,now());return{ok:true,id,message:'Lời mời có hiệu lực 48 giờ; chấp thuận chỉ mở bước xác nhận cuối.'}},
 acceptPartner(receiver:string,id:string){const x=db.prepare("SELECT * FROM partner_invites WHERE id=? AND receiver_id=? AND status='INVITE_PENDING' AND expires_at>?").get(id,receiver,now()) as any;if(!x)return{ok:false,message:'Lời mời không còn hợp lệ.'};db.prepare("UPDATE partner_invites SET status='ACCEPTED_PENDING_CONFIRM',expires_at=? WHERE id=?").run(now()+30*60_000,id);return{ok:true,message:'Đã chấp thuận; hai bên cần xác nhận cuối trong 30 phút.'}},
 confirmPartner(uid:string,id:string){const x=db.prepare("SELECT * FROM partner_invites WHERE id=? AND status='ACCEPTED_PENDING_CONFIRM' AND expires_at>?").get(id,now()) as any;if(!x||![x.sender_id,x.receiver_id].includes(uid))return{ok:false,message:'Phiên xác nhận không hợp lệ.'};db.prepare(`UPDATE partner_invites SET ${uid===x.sender_id?'confirmed_a':'confirmed_b'}=1 WHERE id=?`).run(id);const after=db.prepare('SELECT * FROM partner_invites WHERE id=?').get(id) as any;if(!after.confirmed_a||!after.confirmed_b)return{ok:true,message:'Đã xác nhận; đang chờ phía còn lại.'};if(activeBond(x.sender_id)||activeBond(x.receiver_id))return{ok:false,message:'Trạng thái quan hệ đã thay đổi.'};const [a,b]=pair(x.sender_id,x.receiver_id),bond=randomUUID();db.transaction(()=>{db.prepare("INSERT INTO partner_bonds(id,player_a,player_b,status,formed_at) VALUES(?,?,?,'ACTIVE',?)").run(bond,a,b,now());db.prepare("UPDATE partner_invites SET status='FORMED' WHERE id=?").run(id)})();return{ok:true,bondId:bond,message:'Hai bên đã kết Đạo Lữ.'}},
 dissolve(uid:string,reason='Tự nguyện Giải Ước'){const b=activeBond(uid);if(!b)return{ok:false,message:'Không có Đạo Lữ đang hoạt động.'};db.transaction(()=>{db.prepare("UPDATE dual_cultivation_sessions SET state='INVALIDATED',updated_at=? WHERE bond_id=? AND state NOT IN ('SETTLED','CANCELLED','INVALIDATED')").run(now(),b.id);db.prepare("UPDATE partner_bonds SET status='ARCHIVED',archived_at=?,archive_reason=? WHERE id=?").run(now(),reason,b.id);for(const p of [b.player_a,b.player_b])db.prepare("INSERT INTO relationship_cooldowns(user_id,kind,available_at) VALUES(?,'DAO_LU',?) ON CONFLICT(user_id,kind) DO UPDATE SET available_at=excluded.available_at").run(p,now()+24*3600_000)})();return{ok:true,message:'Quan hệ đã lưu trữ riêng tư; không mất Tu Vi, LT, item hay tiến trình cá nhân. Cooldown lập quan hệ mới: 24 giờ.'}},
 proposeDual(uid:string,energy:30|60|90){const b=activeBond(uid);if(!b)return{ok:false,message:'Song Tu chỉ mở cho Đạo Lữ ACTIVE.'};const stage=bondStage(b.id),rank=['DONG_DAO','SONG_HANH','TUONG_TRI','TUONG_CHIEU'].indexOf(stage);if((energy===60&&rank<1)||(energy===90&&rank<2))return{ok:false,message:'Duyên Trình chưa đủ cho mức Khí Lực này.'};const since=now()-7*86400_000,count=(db.prepare("SELECT COUNT(*) n FROM dual_cultivation_sessions WHERE bond_id=? AND state='SETTLED' AND settled_at>?").get(b.id,since) as any).n,last=(db.prepare("SELECT MAX(settled_at) t FROM dual_cultivation_sessions WHERE bond_id=? AND state='SETTLED'").get(b.id) as any).t||0;if(count>=3||now()-last<20*3600_000)return{ok:false,message:'Đã chạm trần 3 phiên/tuần hoặc cooldown 20 giờ chưa hết.'};const id=randomUUID();db.prepare("INSERT INTO dual_cultivation_sessions(id,bond_id,proposer_id,state,energy,created_at,updated_at) VALUES(?,?,?,'PROPOSED',?,?,?)").run(id,b.id,uid,energy,now(),now());return{ok:true,id,message:'Đã tạo preview Song Tu; cần cả hai xác nhận.'}},
 confirmDual(uid:string,id:string){const s=db.prepare("SELECT s.*,b.player_a,b.player_b FROM dual_cultivation_sessions s JOIN partner_bonds b ON b.id=s.bond_id WHERE s.id=? AND b.status='ACTIVE'").get(id) as any;if(!s||![s.player_a,s.player_b].includes(uid)||!['PROPOSED','BOTH_CONFIRMED'].includes(s.state))return{ok:false,message:'Phiên Song Tu không hợp lệ.'};db.prepare(`UPDATE dual_cultivation_sessions SET ${uid===s.player_a?'confirmed_a':'confirmed_b'}=1,updated_at=? WHERE id=?`).run(now(),id);const x=db.prepare('SELECT * FROM dual_cultivation_sessions WHERE id=?').get(id) as any;if(!x.confirmed_a||!x.confirmed_b)return{ok:true,message:'Đã xác nhận; đang chờ phía còn lại.'};const a=userRepository.get(s.player_a)!,b=userRepository.get(s.player_b)!;if(a.stamina<s.energy||b.stamina<s.energy)return{ok:false,message:'Một bên không còn đủ Khí Lực tại thời điểm khóa.'};const domains=new Set((db.prepare('SELECT domain FROM bond_milestones WHERE bond_id=?').all(s.bond_id) as any[]).map(z=>z.domain)).size,harmony=Math.min(.10,.04+.02*domains),reward=(u:any)=>Math.round((u.exp_needed*(s.energy/500)*.8)*(1+harmony)),ra=reward(a),rb=reward(b),receipt=`songtu:${id}`;return runtimeKernel.execute(receipt,'RELATIONSHIP',uid,'DUAL_CULTIVATION_SETTLE',()=>{db.prepare('UPDATE users SET stamina=stamina-?,tu_vi=tu_vi+? WHERE discord_id=?').run(s.energy,ra,s.player_a);db.prepare('UPDATE users SET stamina=stamina-?,tu_vi=tu_vi+? WHERE discord_id=?').run(s.energy,rb,s.player_b);db.prepare("UPDATE dual_cultivation_sessions SET state='SETTLED',reward_a=?,reward_b=?,confirmed_a=1,confirmed_b=1,receipt_key=?,updated_at=?,settled_at=? WHERE id=?").run(ra,rb,receipt,now(),now(),id);return{ok:true,rewardA:ra,rewardB:rb,message:`Cộng hưởng ổn định; hai bên lần lượt nhận ${ra} và ${rb} Tu Vi.`}}).value},
 bond(uid:string){const b=activeBond(uid);return b?{...b,stage:bondStage(b.id),milestones:db.prepare('SELECT * FROM bond_milestones WHERE bond_id=?').all(b.id)}:null}
};

export const mentorshipRuntime={
 pending(uid:string){return db.prepare("SELECT * FROM mentorship_invites WHERE status='INVITED' AND expires_at>? AND (mentor_id=? OR disciple_id=?) ORDER BY created_at DESC LIMIT 1").get(now(),uid,uid) as any},
 propose(mentor:string,disciple:string){if(mentor===disciple||!userRepository.get(mentor)||!userRepository.get(disciple)||db.prepare("SELECT 1 FROM mentorship_bonds WHERE disciple_id=? AND status='ACTIVE'").get(disciple))return{ok:false,message:'Không thể lập lời mời Sư Đồ.'};const id=randomUUID();db.prepare("INSERT INTO mentorship_invites(id,mentor_id,disciple_id,status,expires_at,created_at) VALUES(?,?,?,'INVITED',?,?)").run(id,mentor,disciple,now()+48*3600_000,now());return{ok:true,id,message:'Lời mời Sư Đồ có hiệu lực 48 giờ.'}},
 confirm(uid:string,id:string){const x=db.prepare("SELECT * FROM mentorship_invites WHERE id=? AND status='INVITED' AND expires_at>?").get(id,now()) as any;if(!x||![x.mentor_id,x.disciple_id].includes(uid))return{ok:false,message:'Lời mời không hợp lệ.'};db.prepare(`UPDATE mentorship_invites SET ${uid===x.mentor_id?'confirmed_mentor':'confirmed_disciple'}=1 WHERE id=?`).run(id);const y=db.prepare('SELECT * FROM mentorship_invites WHERE id=?').get(id) as any;if(!y.confirmed_mentor||!y.confirmed_disciple)return{ok:true,message:'Đã xác nhận; đang chờ phía còn lại.'};const bond=randomUUID();db.transaction(()=>{db.prepare("INSERT INTO mentorship_bonds(id,mentor_id,disciple_id,status,formed_at) VALUES(?,?,?,'ACTIVE',?)").run(bond,x.mentor_id,x.disciple_id,now());db.prepare("UPDATE mentorship_invites SET status='FORMED' WHERE id=?").run(id);db.prepare('INSERT INTO mentorship_milestones(bond_id,milestone,domain,receipt_key,created_at) VALUES(?,?,?,?,?)').run(bond,'FORMED','RELATIONSHIP',`mentor:${bond}:formed`,now())})();return{ok:true,bondId:bond,message:'Quan hệ Sư Đồ đã hình thành.'}},
 guide(mentor:string,bondId:string,domain:string,sourceActivity:string,adviceId:string){const b=db.prepare("SELECT * FROM mentorship_bonds WHERE id=? AND mentor_id=? AND status='ACTIVE'").get(bondId,mentor) as any;if(!b||!sourceActivity)return{ok:false,message:'Chỉ Điểm cần quan hệ ACTIVE và activity ledger thật.'};const id=randomUUID();db.prepare("INSERT INTO guidance_receipts(id,bond_id,domain,source_activity,advice_id,state,expires_at,created_at) VALUES(?,?,?,?,?,'AVAILABLE',?,?)").run(id,bondId,domain,sourceActivity,adviceId,now()+7*86400_000,now());db.prepare('INSERT OR IGNORE INTO mentorship_milestones(bond_id,milestone,domain,receipt_key,created_at) VALUES(?,?,?,?,?)').run(bondId,'FIRST_GUIDANCE',domain,`guidance:${id}`,now());return{ok:true,id,message:'Đã ghi Chỉ Điểm; Guidance Assist hết hạn sau 7 ngày và không stack.'}},
 lesson(mentor:string,bondId:string,lawId:string,lessonNo:1|2|3,policy:string,activityReceipt:string){const b=db.prepare("SELECT * FROM mentorship_bonds WHERE id=? AND mentor_id=? AND status='ACTIVE'").get(bondId,mentor) as any;if(!b||policy!=='PLAYER_TEACHABLE'||!activityReceipt)return{ok:false,message:'Pháp này không thuộc loại có thể truyền qua Sư Đồ hoặc thiếu activity receipt.'};if(lessonNo>1&&!db.prepare("SELECT 1 FROM teaching_lessons WHERE bond_id=? AND law_id=? AND lesson_no=? AND state='COMPLETED'").get(bondId,lawId,lessonNo-1))return{ok:false,message:'Lesson chain phải theo thứ tự.'};const last=(db.prepare('SELECT MAX(created_at) t FROM teaching_lessons WHERE bond_id=? AND law_id=?').get(bondId,lawId) as any).t||0;if(now()-last<20*3600_000)return{ok:false,message:'Cooldown bài học 20 giờ chưa kết thúc.'};const key=`lesson:${bondId}:${lawId}:${lessonNo}`;db.prepare("INSERT INTO teaching_lessons(bond_id,law_id,lesson_no,state,receipt_key,created_at) VALUES(?,?,?,'COMPLETED',?,?)").run(bondId,lawId,lessonNo,key,now());return{ok:true,message:lessonNo===3?'Đồ đệ đã mở mức Nhập Môn với provenance Sư Thừa.':'Đã hoàn thành một bài trong lesson chain.'}},
 end(uid:string,bondId:string,graduated=false){const b=db.prepare("SELECT * FROM mentorship_bonds WHERE id=? AND status='ACTIVE' AND (mentor_id=? OR disciple_id=?)").get(bondId,uid,uid) as any;if(!b)return{ok:false,message:'Không có quan hệ Sư Đồ ACTIVE.'};db.prepare('UPDATE mentorship_bonds SET status=?,ended_at=? WHERE id=?').run(graduated?'XUAT_SU':'DISSOLVED',now(),bondId);for(const p of [b.mentor_id,b.disciple_id])db.prepare("INSERT INTO relationship_cooldowns(user_id,kind,available_at) VALUES(?,'SU_DO',?) ON CONFLICT(user_id,kind) DO UPDATE SET available_at=excluded.available_at").run(p,now()+24*3600_000);return{ok:true,message:graduated?'Đã Xuất Sư; Sư Thừa và ký ức được giữ lại.':'Quan hệ chuyển thành Cựu Sư Đồ; cooldown 24 giờ.'}}
};

export const npcCompanionRuntime={
 current(uid:string){return db.prepare("SELECT * FROM npc_companion_states WHERE user_id=? AND state='ACCOMPANYING'").get(uid) as any},
 invite(uid:string,npcId:string,activityId:string,scope:'PRIVATE'|'PUBLIC'='PRIVATE'){const npc=npcById(npcId),knowledge=db.prepare("SELECT * FROM player_npc_knowledge WHERE user_id=? AND npc_id=? AND stage IN ('eligible','trusted','close')").get(uid,npcId) as any,presence=db.prepare("SELECT * FROM npc_presence WHERE npc_id=? AND state='available'").get(npcId) as any,active=db.prepare("SELECT 1 FROM npc_companion_states WHERE user_id=? AND state='ACCOMPANYING'").get(uid);if(!npc||npc.lifeState!=='current'||!knowledge||!presence||active)return{ok:false,message:'NPC chưa khả dụng: cần quan hệ hợp lệ, có mặt và không có Đồng Hành thường trực khác.'};const key=`npc:${npcId}:${activityId}`;try{db.transaction(()=>{db.prepare("INSERT INTO npc_activity_leases(lease_key,npc_id,player_id,activity_id,scope,state,expires_at,created_at) VALUES(?,?,?,?,?,'ACTIVE',?,?)").run(key,npcId,uid,activityId,scope,now()+2*3600_000,now());db.prepare("INSERT INTO npc_companion_states(user_id,npc_id,state,activity_id,updated_at) VALUES(?,?,'ACCOMPANYING',?,?) ON CONFLICT(user_id,npc_id) DO UPDATE SET state='ACCOMPANYING',activity_id=excluded.activity_id,updated_at=excluded.updated_at").run(uid,npcId,activityId,now());if(scope==='PUBLIC')db.prepare("UPDATE npc_presence SET state='leased',lease_key=?,lease_expires_at=?,updated_at=? WHERE npc_id=?").run(key,now()+2*3600_000,now(),npcId)})();return{ok:true,leaseKey:key,message:`${npc.name} đã nhận lời Đồng Hành.`}}catch{return{ok:false,message:'NPC đã ở trong shared activity instance khác.'}}},
  settle(uid:string,npcId:string,activityId:string,summary:string){const key=`npc:${npcId}:${activityId}`,lease=db.prepare("SELECT * FROM npc_activity_leases WHERE lease_key=? AND player_id=? AND state='ACTIVE'").get(key,uid) as any;if(!lease)return{ok:false,message:'Không có ActivityLease hợp lệ.'};return runtimeKernel.execute(`npc-settle:${key}`,'NPC_COMPANION',uid,'SETTLE',()=>{db.prepare("UPDATE npc_activity_leases SET state='SETTLED' WHERE lease_key=?").run(key);db.prepare("UPDATE npc_companion_states SET state='RESTING',activity_id=NULL,rest_until=?,updated_at=? WHERE user_id=? AND npc_id=?").run(now()+2*3600_000,now(),uid,npcId);db.prepare("UPDATE npc_presence SET state='available',lease_key=NULL,lease_expires_at=NULL,updated_at=? WHERE npc_id=? AND lease_key=?").run(now(),npcId,key);db.prepare('INSERT OR IGNORE INTO npc_memories(user_id,npc_id,memory_key,payload_json,created_at) VALUES(?,?,?,?,?)').run(uid,npcId,`activity:${activityId}`,JSON.stringify({summary}),now());return{ok:true,message:'Chuyến Đồng Hành đã quyết toán; ký ức và thời gian nghỉ được ghi nhận.'}}).value}
};
