import {randomUUID} from 'crypto';
import db from '../database/database';
import {statsService} from './StatsService';
import {combatEngine} from './CombatEngineService';
import {runtimeKernel} from './RuntimeKernelService';

const now=()=>Date.now();
export const towerService={
 active(uid:string){return db.prepare("SELECT * FROM tower_runs WHERE user_id=? AND state IN ('READY','FLOOR_TERMINAL') ORDER BY created_at DESC LIMIT 1").get(uid) as any},
 start(uid:string){const old=this.active(uid);if(old)return{ok:true,replayed:true,runId:old.id,message:'Tiếp tục run Vấn Chiến Tháp hiện tại.'};const s=statsService.get(uid);if(!s)return{ok:false,message:'Chưa có đạo hồ.'};const id=randomUUID();db.prepare("INSERT INTO tower_runs(id,user_id,mode,state,current_floor,snapshot_json,created_at,updated_at) VALUES(?,?,'SOLO','READY',1,?,?,?)").run(id,uid,JSON.stringify({basePower:s.power,startedStats:s}),now(),now());return{ok:true,runId:id,message:'Đã khóa run Thương Mang Vấn Chiến Tháp · 36 tầng.'}},
 challenge(uid:string){const run=this.active(uid);if(!run||run.state!=='READY'||run.current_floor>36)return{ok:false,message:'Không có tầng đang chờ khiêu chiến.'};const s=statsService.get(uid)!,floor=run.current_floor,band=.55+floor*.035,boss=floor%6===0,enemy={id:`tower:${floor}`,name:boss?`Thủ Tầng · Trọng Quan ${floor}`:`Thủ Tầng ${floor}`,hp:Math.floor(s.hp*(boss?1.55:1.05)*band),atk:Math.floor(s.atk*(boss?1.12:.82)*band),def:Math.floor(s.def*(boss?1.08:.8)*band),speed:90+floor};const fight=combatEngine.start({mode:'TOWER',sourceId:`tower:${run.id}`,sourceRunId:`floor:${floor}`,players:[uid],enemies:[enemy],seed:`tower:${run.id}:${floor}`});const replay=combatEngine.replay(fight.encounterId)!,terminal=replay.result.terminal;combatEngine.settle(fight.encounterId,`tower:${run.id}:floor:${floor}`);const reward=terminal==='VICTORY'?{lt:floor%3===0?floor*80:0,tuvi:floor*12}:{};db.transaction(()=>{db.prepare('INSERT INTO tower_floor_receipts(run_id,floor_no,encounter_id,terminal,reward_json,created_at) VALUES(?,?,?,?,?,?)').run(run.id,floor,fight.encounterId,terminal,JSON.stringify(reward),now());if(terminal==='VICTORY'){if(reward.lt||reward.tuvi)db.prepare('UPDATE users SET coin_ha_pham=coin_ha_pham+?,tu_vi=tu_vi+? WHERE discord_id=?').run(reward.lt||0,reward.tuvi||0,uid);db.prepare('UPDATE tower_runs SET highest_floor=?,current_floor=?,state=?,updated_at=?,settled_at=? WHERE id=?').run(floor,floor+1,floor===36?'SETTLED':'READY',now(),floor===36?now():null,run.id)}else db.prepare("UPDATE tower_runs SET state='FAILED',updated_at=?,settled_at=? WHERE id=?").run(now(),now(),run.id)})();return{ok:true,terminal,floor,reward,message:terminal==='VICTORY'?(floor===36?'Đã hoàn thành toàn bộ 36 tầng.':`Đã vượt tầng ${floor}.`):`Dừng bước tại tầng ${floor}; run kết thúc.`}},
 history(uid:string){return db.prepare('SELECT * FROM tower_runs WHERE user_id=? ORDER BY created_at DESC LIMIT 10').all(uid) as any[]},
 audit(){const errors:string[]=[];for(const r of db.prepare('SELECT * FROM tower_runs').all() as any[]){const count=(db.prepare('SELECT COUNT(*) n FROM tower_floor_receipts WHERE run_id=?').get(r.id) as any).n;if(count!==r.highest_floor&&r.state!=='FAILED')errors.push(`${r.id}: floor receipt mismatch`);if(r.highest_floor>36)errors.push(`${r.id}: floor overflow`)}return errors}
};
