import {Interaction,MessageFlags} from 'discord.js';import {TuTienClient} from '../client/TuTienClient';import {safeUpdate,sellModal,auctionCreateModal,auctionBidModal,appearanceModal,announcementModal,ownerAssetModal,ownerItemModal,ownerPlayerModal,ownerContentModal,ownerRepairModal,sectCreateModal} from '../utils/ui';import {userRepository} from '../database/repositories/UserRepository';
import {homeView,profileView,systemView,inventoryView,storageView,bagCraftView,temporaryView,vaultView,heirloomView,instanceLedgerView,worldView,branchView,craftView,recipesView,recipeDetailView,dutyView,knowledgeView,encyListView,encyEntryView,shopView,combatView,cultivationView,npcShopView,cpltShopView,marketView,auctionView,bossesView,realmsView,pvpView,dongPhuView,lineageView,relationsView,askLangTieuView,journeyView,sectView,rankingView,farmView,partyView,eventsView,towerView,langTieuRealmVisitView} from '../services/TuTienUIService';
import {worldService} from '../services/WorldService';import {craftingService} from '../services/CraftingService';import {dutyService} from '../services/DutyService';import {equipmentService} from '../services/EquipmentService';import {consumableService} from '../services/ConsumableService';import {cultivationService} from '../services/CultivationService';import {marketService} from '../services/MarketService';import {combatService} from '../services/CombatService';import {Branch,LOCATIONS,RECIPES} from '../config/GameCatalog';
import {journeyService} from '../services/JourneyService';
import {storageService} from '../services/StorageService';import {inventoryRepository} from '../database/repositories/InventoryRepository';
import {itemInstanceService} from '../services/ItemInstanceService';
import {companionRuntime,dutyRuntime,eventRuntime,farmRuntime,intentRuntime,partyRuntime,qilingRuntime,sectRuntime} from '../services/RuntimeSystemsService';
import {isBotOwner} from '../config/permissions';
import {worldEventGameplay} from '../services/WorldEventGameplayService';
import {auctionService} from '../services/AuctionService';
import {appearanceService} from '../services/AppearanceService';
import {ownerControlService} from '../services/OwnerControlService';import {ownerMutationConfirmView,ownerResetConfirmView,ownerView} from '../services/OwnerUIService';import {ownerAdvancedService} from '../services/OwnerAdvancedService';
import {ownerApprovalService} from '../services/OwnerApprovalService';
import {dungeonPartyService} from '../services/DungeonPartyService';import {playerSectService} from '../services/PlayerSectService';import {mentorshipRuntime,npcCompanionRuntime,relationshipRuntime} from '../services/RelationshipRuntimeService';import {anomalyRuntime,rareDutyRuntime} from '../services/ActivityRuntimeService';import {towerService} from '../services/TowerService';import {randomUUID} from 'crypto';
import {realmNpcVisitService} from '../services/RealmNpcVisitService';
import {UI_ACTIONS} from '../config/SystemRegistry';
import {operationalHardeningService} from '../services/OperationalHardeningService';
function parse(customId:string){const k=customId.lastIndexOf('_');const left=customId.slice(0,k),uid=customId.slice(k+1);const p=left.slice(2).split(':');return{action:p.shift()||'',extra:p.join(':'),uid}}
async function dispatchInteraction(client:TuTienClient,i:Interaction){
 if(i.isChatInputCommand()){if(!i.deferred&&!i.replied)await i.deferReply({flags:MessageFlags.Ephemeral});const c=client.commands.get(i.commandName);if(c)await c.execute(client,i);else await i.editReply('Lệnh này chưa được đăng ký.');return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttmarketsellmodal_')){const uid=i.customId.slice('ttmarketsellmodal_'.length);if(i.user.id!==uid){await i.reply({content:'Đây không phải giao diện của đạo hữu.',flags:MessageFlags.Ephemeral});return}const qty=Number(i.fields.getTextInputValue('qty')),price=Number(i.fields.getTextInputValue('price')),item=i.fields.getTextInputValue('item');const r=marketService.create(uid,item,qty,price);await i.reply({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttauctioncreatemodal:')){const {extra,uid}=parse(i.customId);if(i.user.id!==uid)return void await i.reply({content:'Đây không phải giao diện của đạo hữu.',flags:MessageFlags.Ephemeral});const r=auctionService.create(uid,extra,Number(i.fields.getTextInputValue('price')),Number(i.fields.getTextInputValue('hours')));await i.reply({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttauctionbidmodal:')){const {extra,uid}=parse(i.customId);if(i.user.id!==uid)return void await i.reply({content:'Đây không phải giao diện của đạo hữu.',flags:MessageFlags.Ephemeral});const r=auctionService.bid(uid,Number(extra),Number(i.fields.getTextInputValue('amount')));await i.reply({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttappearancemodal:')){const {extra,uid}=parse(i.customId);if(i.user.id!==uid)return void await i.reply({content:'Đây không phải giao diện của đạo hữu.',flags:MessageFlags.Ephemeral});const r=appearanceService.update(uid,extra as any,i.fields.getTextInputValue('url'));await i.reply({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttsectcreatemodal_')){const uid=i.customId.slice('ttsectcreatemodal_'.length);if(i.user.id!==uid)return void await i.reply({content:'Đây không phải giao diện của đạo hữu.',flags:MessageFlags.Ephemeral});const r=playerSectService.create(uid,i.fields.getTextInputValue('name'),`ui:sect:create:${uid}:${i.id}`);await i.reply({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttannouncementmodal:')){const {extra,uid}=parse(i.customId);if(i.user.id!==uid||!isBotOwner(uid))return void await i.reply({content:'Thiên Thư không nhận chủ.',flags:MessageFlags.Ephemeral});const r=ownerControlService.announce(uid,extra,i.fields.getTextInputValue('content'));if(r.ok&&i.channel?.isSendable())await i.channel.send(r.message);await i.reply({content:r.ok?'Đã ban bố cáo thị.':r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttownerassetmodal:')){const {extra,uid}=parse(i.customId),[op,asset]=extra.split('~');if(i.user.id!==uid||!isBotOwner(uid))return void await i.reply({content:'Thiên Thư không nhận chủ.',flags:MessageFlags.Ephemeral});const target=i.fields.getTextInputValue('target'),amount=Number(i.fields.getTextInputValue('amount')),r=asset==='CPLT'?ownerApprovalService.previewCplt(uid,target,op as any,amount):ownerControlService.adjustCurrency(uid,target,asset as any,op as any,amount);if(asset==='CPLT'&&r.ok)await i.reply({components:[ownerMutationConfirmView(uid,r,'ownerhighconfirm')],flags:32832} as any);else await i.reply({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttowneritemmodal:')){const {extra,uid}=parse(i.customId);if(i.user.id!==uid||!isBotOwner(uid))return void await i.reply({content:'Thiên Thư không nhận chủ.',flags:MessageFlags.Ephemeral});const r=ownerControlService.adjustItem(uid,i.fields.getTextInputValue('target'),i.fields.getTextInputValue('item'),extra as any,Number(i.fields.getTextInputValue('amount')));await i.reply({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttownerplayermodal:')){const {extra,uid}=parse(i.customId);if(i.user.id!==uid||!isBotOwner(uid))return void await i.reply({content:'Thiên Thư không nhận chủ.',flags:MessageFlags.Ephemeral});const r=ownerAdvancedService.previewPlayer(uid,i.fields.getTextInputValue('target'),extra as any,i.fields.getTextInputValue('value'),i.fields.getTextInputValue('reason'));if(r.ok)await i.reply({components:[ownerMutationConfirmView(uid,r)],flags:32832} as any);else await i.reply({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttownercontentmodal:')){const {extra,uid}=parse(i.customId);if(i.user.id!==uid||!isBotOwner(uid))return void await i.reply({content:'Thiên Thư không nhận chủ.',flags:MessageFlags.Ephemeral});const id=i.fields.getTextInputValue('definition_id'),v=i.fields.getTextInputValue('kind'),data=i.fields.getTextInputValue('data');if(extra!=='DRAFT'&&data.trim()!=='CONFIRM')return void await i.reply({content:'Phải nhập đúng `CONFIRM`.',flags:MessageFlags.Ephemeral});const r=extra==='DRAFT'?ownerAdvancedService.draftContent(uid,id,v,data):ownerApprovalService.previewContent(uid,id,Number(v),extra as any);if(extra!=='DRAFT'&&r.ok)await i.reply({components:[ownerMutationConfirmView(uid,r,'ownerhighconfirm')],flags:32832} as any);else await i.reply({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isModalSubmit()&&i.customId.startsWith('ttownerrepairmodal_')){const uid=i.customId.slice('ttownerrepairmodal_'.length);if(i.user.id!==uid||!isBotOwner(uid))return void await i.reply({content:'Thiên Thư không nhận chủ.',flags:MessageFlags.Ephemeral});const parts=i.fields.getTextInputValue('reason').split('|'),r=ownerApprovalService.previewRepair(uid,i.fields.getTextInputValue('target'),i.fields.getTextInputValue('field') as any,Number(i.fields.getTextInputValue('value')),parts[0]?.trim()||'',parts[1]?.trim()||'',i.fields.getTextInputValue('key'));if(r.ok)await i.reply({components:[ownerMutationConfirmView(uid,r,'ownerhighconfirm')],flags:32832} as any);else await i.reply({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isUserSelectMenu()&&i.customId.startsWith('ttpvpselect')){const {uid}=parse(i.customId);if(i.user.id!==uid){await i.reply({content:'Đây không phải ngọc giản của đạo hữu.',flags:MessageFlags.Ephemeral});return}const r=combatService.pvp(uid,i.values[0]);await safeUpdate(i,pvpView(uid));await i.followUp({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isUserSelectMenu()&&i.customId.startsWith('ttpartyinvite_select')){const {uid}=parse(i.customId);if(i.user.id!==uid)return void await i.reply({content:'Đây không phải giao diện của đạo hữu.',flags:MessageFlags.Ephemeral});const r=dungeonPartyService.invite(uid,i.values[0]);await safeUpdate(i,partyView(uid));await i.followUp({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isUserSelectMenu()&&i.customId.startsWith('ttdaoluproposeselect')){const {uid}=parse(i.customId);if(i.user.id!==uid)return void await i.reply({content:'Đây không phải giao diện của đạo hữu.',flags:MessageFlags.Ephemeral});const r=relationshipRuntime.proposePartner(uid,i.values[0]);await safeUpdate(i,relationsView(uid));await i.followUp({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(i.isUserSelectMenu()&&i.customId.startsWith('ttmentorproposeselect')){const {uid}=parse(i.customId);if(i.user.id!==uid)return void await i.reply({content:'Đây không phải giao diện của đạo hữu.',flags:MessageFlags.Ephemeral});const r=mentorshipRuntime.propose(uid,i.values[0]);await safeUpdate(i,relationsView(uid));await i.followUp({content:r.message,flags:MessageFlags.Ephemeral});return}
 if(!i.isButton()||!i.customId.startsWith('tt'))return;
 const {action,extra,uid}=parse(i.customId);if(i.user.id!==uid){await i.reply({content:'Đây không phải ngọc giản của đạo hữu.',flags:MessageFlags.Ephemeral});return}if(!(UI_ACTIONS as readonly string[]).includes(action)){await i.reply({content:'Nút này không còn hiệu lực hoặc thuộc phiên bản giao diện cũ.',flags:MessageFlags.Ephemeral});return}if(ownerControlService.maintenanceLocked()&&!action.startsWith('owner')){await i.reply({content:'Thiên hạ đang trong maintenance để xác nhận reset; thao tác gameplay tạm khóa.',flags:MessageFlags.Ephemeral});return}if(!userRepository.get(uid)&&!action.startsWith('owner')){await i.reply({content:'Đạo hữu chưa nhập thế. Hãy dùng /taonhanvat trước.',flags:MessageFlags.Ephemeral});return}
 if(action==='marketsell'||action==='instsell'){await i.showModal(sellModal(uid,action==='instsell'?extra:''));return}if(action==='auctioncreate'){await i.showModal(auctionCreateModal(uid,extra));return}if(action==='auctionbid'){const[l,min]=extra.split('~');await i.showModal(auctionBidModal(uid,Number(l),Number(min)));return}if(action==='appearanceavatar'||action==='appearancethumb'){await i.showModal(appearanceModal(uid,action==='appearanceavatar'?'avatar_url':'thumbnail_url'));return}if(action==='sectcreateform'){await i.showModal(sectCreateModal(uid));return}if(action==='ownerannounceform'){if(!isBotOwner(uid))throw new Error('OWNER_ONLY');await i.showModal(announcementModal(uid,extra));return}if(action==='ownerassetform'){if(!isBotOwner(uid))throw new Error('OWNER_ONLY');const[op,asset]=extra.split('~');await i.showModal(ownerAssetModal(uid,op,asset));return}if(action==='owneritemform'){if(!isBotOwner(uid))throw new Error('OWNER_ONLY');await i.showModal(ownerItemModal(uid,extra));return}if(action==='ownerplayerform'){if(!isBotOwner(uid))throw new Error('OWNER_ONLY');await i.showModal(ownerPlayerModal(uid,extra));return}if(action==='ownercontentform'){if(!isBotOwner(uid))throw new Error('OWNER_ONLY');await i.showModal(ownerContentModal(uid,extra));return}if(action==='ownerrepairform'){if(!isBotOwner(uid))throw new Error('OWNER_ONLY');await i.showModal(ownerRepairModal(uid));return}
 let view:any,notice='';
 switch(action){
  case'ownerhighconfirm':{if(!isBotOwner(uid))throw new Error('OWNER_ONLY');const[mid,nonce]=extra.split('~'),r=ownerApprovalService.confirm(uid,mid,nonce);notice=r.message;view=ownerView(uid);break}
  case'home':view=homeView(uid);break;case'profile':view=profileView(uid);break;case'system':view=systemView(uid);break;case'appearancereset':notice=appearanceService.resetThumbnail(uid).message;view=systemView(uid);break;case'dongphu':view=dongPhuView(uid);break;case'langtieuvisit':view=langTieuRealmVisitView(uid,extra);break;case'langtieuvisitchoice':{const[visit,choice]=extra.split('~');notice=realmNpcVisitService.choose(uid,visit,choice).message;view=langTieuRealmVisitView(uid,visit);break}case'langtieuvisitclose':notice=realmNpcVisitService.close(uid,extra).message;view=dongPhuView(uid);break;case'inventory':view=inventoryView(uid);break;
  case'storage':view=storageView(uid);break;case'bagcrafts':view=bagCraftView(uid);break;case'bagcraft':notice=storageService.craft(uid,extra).message;view=bagCraftView(uid);break;case'bagswitch':notice=storageService.switchBag(uid,Number(extra)).message;view=storageView(uid);break;
  case'baglearn':notice=storageService.learn(uid,extra).message;view=bagCraftView(uid);break;
  case'temporary':view=temporaryView(uid);break;case'tempclaim':notice=inventoryRepository.claimTemporary(uid,extra).message;view=temporaryView(uid);break;case'tempvault':notice=inventoryRepository.moveTemporaryToVault(uid,extra).message;view=temporaryView(uid);break;case'vault':view=vaultView(uid);break;case'vaultclaim':notice=inventoryRepository.claimVault(uid,extra).message;view=vaultView(uid);break;
  case'instequip':notice=itemInstanceService.equip(uid,extra).message;view=inventoryView(uid);break;case'instrepair':notice=itemInstanceService.repair(uid,extra).message;view=inventoryView(uid);break;case'instclaim':notice=itemInstanceService.claim(uid,extra).message;view=inventoryView(uid);break;case'instvault':notice=itemInstanceService.moveToVault(uid,extra).message;view=temporaryView(uid);break;
  case'wardrestore':notice=itemInstanceService.restoreWard(uid,extra).message;view=inventoryView(uid);break;
  case'heirloom':view=heirloomView(uid);break;case'heirloomidentify':notice=itemInstanceService.identifyHeirloom(uid,extra).message;view=heirloomView(uid);break;
  case'instances':view=instanceLedgerView(uid);break;
  case'cultivation':view=cultivationView(uid);break;case'meditate':notice=cultivationService.meditate(uid).message;view=action==='meditate'?dongPhuView(uid):cultivationView(uid);break;case'breakthrough':notice=cultivationService.breakthrough(uid).message;view=dongPhuView(uid);break;

  case'lingcan':view=lineageView(uid,'lingcan');break;case'qiling':view=lineageView(uid,'qiling');break;case'pet':view=lineageView(uid,'pet');break;case'mount':view=lineageView(uid,'mount');break;case'ycanh':view=lineageView(uid,'ycanh');break;case'daotam':view=lineageView(uid,'daotam');break;
  case'tongmon':view=sectView(uid);break;case'sectjoin':notice=sectRuntime.join(uid,extra).message;view=sectView(uid);break;case'sectleave':notice=(sectRuntime.get(uid)?.sect_id?.startsWith('ps:')?playerSectService.leave(uid):sectRuntime.leave(uid)).message;view=sectView(uid);break;case'sectactivity':notice=sectRuntime.activity(uid).message;view=sectView(uid);break;case'playersectmission':notice=`Đã nạp ${playerSectService.ensureDailyMission(uid).length} nhiệm vụ riêng.`;view=sectView(uid);break;case'ranking':view=rankingView(uid);break;case'lingtian':view=farmView(uid);break;case'farmplant':notice=farmRuntime.plant(uid,Number(extra)).message;view=farmView(uid);break;case'farmharvest':notice=farmRuntime.harvest(uid,Number(extra)).message;view=farmView(uid);break;
  case'relations':view=relationsView(uid);break;case'asklt':view=askLangTieuView(uid,extra||'small_talk');break;case'daoluaccept':notice=relationshipRuntime.acceptPartner(uid,extra).message;view=relationsView(uid);break;case'daoluconfirm':notice=relationshipRuntime.confirmPartner(uid,extra).message;view=relationsView(uid);break;case'daoludissolve':notice=relationshipRuntime.dissolve(uid).message;view=relationsView(uid);break;case'songtupropose':notice=relationshipRuntime.proposeDual(uid,Number(extra) as 30|60|90).message;view=relationsView(uid);break;case'songtuconfirm':notice=relationshipRuntime.confirmDual(uid,extra).message;view=relationsView(uid);break;case'mentorconfirm':notice=mentorshipRuntime.confirm(uid,extra).message;view=relationsView(uid);break;case'npccompinvite':notice=npcCompanionRuntime.invite(uid,extra,`free_roam:${uid}:${Date.now()}`).message;view=relationsView(uid);break;case'npccompsettle':{const[npc,activity]=extra.split('~');notice=npcCompanionRuntime.settle(uid,npc,activity,'Kết thúc chuyến Đồng Hành từ giao diện Duyên Phận.').message;view=relationsView(uid);break}
  case'journey':view=journeyView(uid);break;
  case'jstart':{const r=journeyService.start(uid,extra);notice=r.ok?'Đã khởi hành Cơ Duyên.':r.message;view=journeyView(uid);break}
  case'jpage':view=journeyView(uid,'',Number(extra)||0);break;
  case'jchoice':{const [jid,choice]=extra.split('~');const r=journeyService.choose(uid,jid,choice);notice=r.message;view=journeyView(uid);break}
  case'jpause':{const r=journeyService.pause(uid,extra);notice=r.message;view=homeView(uid);break}
  case'world':view=worldView(uid);break;case'branch':view=branchView(uid,extra as Branch);break;
  case'act':{const r=worldService.act(uid,extra);notice=r.message;const loc=LOCATIONS.find(x=>x.id===extra);view=loc?branchView(uid,loc.branch):worldView(uid);break}
  case'craft':view=craftView(uid);break;case'recipes':{const [kind,p='0']=extra.split(':');view=recipesView(uid,kind as any,Number(p)||0);break}case'recipedetail':view=recipeDetailView(uid,extra);break;
  case'craftdo':{const [rid,n='1']=extra.split('~'),r=craftingService.craftMany(uid,rid,Number(n));notice=r.message;view=recipeDetailView(uid,rid);break}
  case'equip':notice=equipmentService.equip(uid,extra).message;view=inventoryView(uid);break;case'use':notice=consumableService.use(uid,extra).message;view=inventoryView(uid);break;
  case'duty':view=dutyView(uid);break;case'dutyclaim2':notice=dutyRuntime.claim(uid,extra).message;view=dutyView(uid);break;case'raredutyresolve':notice=rareDutyRuntime.resolve(uid,extra,`ui:rare:${uid}:${extra}`).message;view=dutyView(uid);break;case'dutyexchange':notice=marketService.exchangeToken(uid,'tranhai_lenh').message;view=dutyView(uid);break;
  case'knowledge':view=knowledgeView(uid);break;case'encycat':{const [t,p='0']=extra.split(':');view=encyListView(uid,t,Number(p)||0);break}case'ency':view=encyEntryView(uid,extra);break;
  case'shop':view=shopView(uid);break;case'npcshop':view=npcShopView(uid);break;case'npcbuy':notice=marketService.buyNpc(uid,extra).message;view=npcShopView(uid);break;case'cpltshop':view=cpltShopView(uid);break;case'cpltbuy':notice=marketService.buyCplt(uid,extra).message;view=cpltShopView(uid);break;
  case'market':view=marketView(uid);break;case'marketbuy':notice=marketService.buy(uid,Number(extra)).message;view=marketView(uid);break;case'marketcancel':notice=marketService.cancel(uid,Number(extra)).message;view=marketView(uid);break;case'auction':view=auctionView(uid);break;
  case'eventattack':notice=worldEventGameplay.attack(uid).message;view=eventsView(uid);break;case'eventheal':notice=worldEventGameplay.healNpc(uid).message;view=eventsView(uid);break;case'eventbreach':notice=worldEventGameplay.breach(uid,extra as any).message;view=eventsView(uid);break;
  case'combat':view=combatView(uid);break;case'combatexchange':notice=marketService.exchangeToken(uid,'xichduc_lenh').message;view=combatView(uid);break;case'bosses':view=bossesView(uid);break;case'bossattack':notice=combatService.attackBoss(uid,extra).message;view=bossesView(uid);break;case'realms':view=realmsView(uid);break;case'realmenter':notice=combatService.secretRealm(uid,extra).message;view=realmsView(uid);break;case'party':view=partyView(uid);break;case'partycreate':notice=dungeonPartyService.create(uid,extra).message;view=partyView(uid);break;case'partyjoin':notice=dungeonPartyService.join(uid,extra).message;view=partyView(uid);break;case'partyready':notice=dungeonPartyService.ready(uid).message;view=partyView(uid);break;case'partystart':notice=dungeonPartyService.start(uid).message;view=partyView(uid);break;case'partyroute':notice=dungeonPartyService.chooseRoute(uid,extra as any).message;view=partyView(uid);break;case'partysettle':notice=dungeonPartyService.settleRoom(uid).message;view=partyView(uid);break;case'partyheal':{const v=dungeonPartyService.view(uid),targets=v?.members.filter((x:any)=>x.hp<x.max_hp).map((x:any)=>x.user_id)||[];notice=dungeonPartyService.healAtCheckpoint(uid,targets).message;view=partyView(uid);break}case'events':view=eventsView(uid);break;case'anomalyact':notice=anomalyRuntime.act(uid,extra).message;view=eventsView(uid);break;case'compfeed':notice=companionRuntime.feed(uid,Number(extra)).message;view=dongPhuView(uid);break;case'compadvance':notice=companionRuntime.advance(uid,Number(extra)).message;view=dongPhuView(uid);break;case'compequip':notice=companionRuntime.equip(uid,Number(extra)).message;view=dongPhuView(uid);break;case'qilinurture':notice=qilingRuntime.nurture(uid,extra).message;view=lineageView(uid,'qiling');break;case'intentpractice':{const[k,s]=extra.split('~');notice=intentRuntime.practice(uid,k as any,s).message;view=lineageView(uid,k==='Y_CANH'?'ycanh':'daotam');break}case'pvp':view=pvpView(uid);break;case'tower':view=towerView(uid);break;case'towerstart':notice=towerService.start(uid).message;view=towerView(uid);break;case'towerchallenge':notice=towerService.challenge(uid).message;view=towerView(uid);break;
  case'ownerpanel':if(!isBotOwner(uid))throw new Error('OWNER_ONLY');view=ownerView(uid);break;case'ownerannounce':if(!isBotOwner(uid))throw new Error('OWNER_ONLY');view=ownerView(uid,'announce');break;case'ownertest':if(!isBotOwner(uid))throw new Error('OWNER_ONLY');notice=ownerControlService.bindTest(uid).message;view=ownerView(uid);break;case'ownerplayers':if(!isBotOwner(uid))throw new Error('OWNER_ONLY');view=ownerView(uid,'players');break;case'ownerplayerconfirm':{if(!isBotOwner(uid))throw new Error('OWNER_ONLY');const[mid,nonce]=extra.split('~'),r=ownerAdvancedService.confirmPlayer(uid,mid,nonce);notice=r.message;view=ownerView(uid,'players');break}case'ownerassets':if(!isBotOwner(uid))throw new Error('OWNER_ONLY');view=ownerView(uid,'assets');break;case'ownerworld':if(!isBotOwner(uid))throw new Error('OWNER_ONLY');view=ownerView(uid,'world');break;case'ownerresetpreview':{if(!isBotOwner(uid))throw new Error('OWNER_ONLY');const r=await ownerControlService.previewReset(uid);if(r.ok)view=ownerResetConfirmView(uid,r);else{notice=r.message;view=ownerView(uid,'world')}break}case'ownerresetconfirm':{if(!isBotOwner(uid))throw new Error('OWNER_ONLY');const[job,nonce]=extra.split('~'),r=ownerControlService.confirmReset(uid,job,nonce);notice=r.message;view=ownerView(uid);break}case'ownercontent':if(!isBotOwner(uid))throw new Error('OWNER_ONLY');view=ownerView(uid,'content');break;case'ownersystem':if(!isBotOwner(uid))throw new Error('OWNER_ONLY');view=ownerView(uid,'system');break;case'ownersystemstatus':{if(!isBotOwner(uid))throw new Error('OWNER_ONLY');const s=ownerAdvancedService.status();notice=`Epoch ${s.epoch} · maintenance ${s.maintenance?'ON':'OFF'} · ${s.users} users · ${s.events} active events · ${s.tables} tables`;view=ownerView(uid,'system');break}case'ownersnapshot':{if(!isBotOwner(uid))throw new Error('OWNER_ONLY');notice=(await ownerAdvancedService.snapshot(uid)).message;view=ownerView(uid,'system');break}case'ownertick':if(!isBotOwner(uid))throw new Error('OWNER_ONLY');notice=`Đã chạy scheduler; mở ${eventRuntime.tick().join(', ')||'0'} hoạt động mới.`;view=ownerView(uid);break;case'owneraudit':if(!isBotOwner(uid))throw new Error('OWNER_ONLY');notice='Nhật ký quản trị nằm trong admin_audit.';view=ownerView(uid);break;
  default:throw new Error(`UNHANDLED_UI_ACTION:${action}`)
 }
 await safeUpdate(i,view);if(notice)await i.followUp({content:notice,flags:MessageFlags.Ephemeral})
}

function interactionKey(i:any){if(i.isChatInputCommand?.())return`command:${i.commandName}`;if(i.customId){const raw=String(i.customId),split=raw.lastIndexOf('_');return`component:${raw.slice(0,split<0?100:split).slice(0,100)}`}return`interaction:${i.type??'unknown'}`}
function discordErrorCode(error:any){return Number(error?.code??error?.rawError?.code??error?.cause?.code??0)}
function expiredInteraction(error:any){const code=discordErrorCode(error),message=String(error?.message??'');return code===10062||code===40060||/Unknown interaction|already been acknowledged/i.test(message)}
async function respond(i:any,content:string){const payload={content,flags:MessageFlags.Ephemeral};if(i.replied||i.deferred)await i.followUp(payload);else await i.reply(payload)}
export async function onInteraction(client:TuTienClient,i:Interaction){const interactionId=String((i as any).id||''),userId=String((i as any).user?.id||''),actionKey=interactionKey(i as any);let received=false;try{
 if(userId&&!operationalHardeningService.allow(userId,actionKey)){await respond(i as any,'Thao tác quá nhanh. Hãy chờ một nhịp rồi thử lại.');return}
 if(interactionId&&userId){received=operationalHardeningService.beginInteraction(interactionId,userId,actionKey);if(!received){await respond(i as any,'Thao tác này đã được tiếp nhận; không thực hiện lần thứ hai.');return}}
 await dispatchInteraction(client,i);if(received)operationalHardeningService.completeInteraction(interactionId)
 }catch(error){if(received)operationalHardeningService.failInteraction(interactionId,error);const ownerDenied=error instanceof Error&&error.message==='OWNER_ONLY';if(expiredInteraction(error)){console.warn('[interaction-expired]',{interactionId,actionKey,user:userId});return}if(!ownerDenied)console.error('[interaction-error]',{kind:(i as any).type,customId:(i as any).customId,command:(i as any).commandName,user:userId,error});try{await respond(i as any,ownerDenied?'Thiên Thư không nhận chủ.':'Thao tác gặp lỗi hiển thị. Hãy mở lại giao diện và kiểm tra trạng thái trước khi thử lại.')}catch(replyError){if(!expiredInteraction(replyError))console.error('[interaction-error-response-failed]',replyError)}}}
