import {REST,Routes} from 'discord.js';import {TuTienClient} from '../client/TuTienClient';import db,{initDatabase} from '../database/database';import {dialogueService} from '../services/DialogueService';
import {eventRuntime} from '../services/RuntimeSystemsService';
import {worldEventGameplay} from '../services/WorldEventGameplayService';
import {rankingSeasonService} from '../services/RankingSeasonService';import {auctionService} from '../services/AuctionService';
import {ownerApprovalService} from '../services/OwnerApprovalService';
import {anomalyRuntime} from '../services/ActivityRuntimeService';
import {runStartupAudit} from '../services/StartupAuditService';
import {operationalHardeningService} from '../services/OperationalHardeningService';
import {deploymentRuntime} from '../services/DeploymentRuntimeService';
let scheduler:NodeJS.Timeout|null=null;
export function runEventCycle(at=Date.now()){if(!operationalHardeningService.acquireSchedulerCycle(at))return{ran:false,recovery:null};const recovery=operationalHardeningService.recover(at),expired=db.prepare("SELECT id FROM world_event_runs WHERE status='ACTIVE' AND ends_at<=?").all(at) as {id:string}[];for(const run of expired)worldEventGameplay.settle(run.id);eventRuntime.tick(at);anomalyRuntime.tick(at);auctionService.settle(at);ownerApprovalService.rejectExpired();const current=rankingSeasonService.keys(at),seasons=db.prepare('SELECT DISTINCT board,season_key FROM ranking_scores').all() as {board:'QUAN_HUNG'|'THIEN_HA',season_key:string}[];for(const s of seasons)if(s.season_key!==(s.board==='QUAN_HUNG'?current.week:current.month))rankingSeasonService.settle(s.board,s.season_key);return{ran:true,recovery}}
export function stopEventScheduler(){if(scheduler){clearInterval(scheduler);scheduler=null}}
export async function onReady(client:TuTienClient){initDatabase();const audit=runStartupAudit([...client.commands.keys()]);if(!audit.ok)throw new Error('Production startup audit failed:\n'+audit.errors.join('\n'));dialogueService.seedPresence();runEventCycle();void deploymentRuntime.snapshotIfDue().catch(error=>deploymentRuntime.log('error','snapshot.failed',{error:String(error)}));scheduler=setInterval(()=>{runEventCycle();void deploymentRuntime.snapshotIfDue().catch(error=>deploymentRuntime.log('error','snapshot.failed',{error:String(error)}))},60_000);scheduler.unref();const rest=new REST({version:'10'}).setToken(client.token!);await rest.put(Routes.applicationCommands(client.user!.id),{body:client.commands.map(c=>c.data.toJSON())});console.log(`✅ ${client.user?.tag} online · ${client.commands.size} slash commands · ${audit.checks} startup checks · scheduler Asia/Ho_Chi_Minh active`)}
