import {ActionRowBuilder,ButtonBuilder,ButtonStyle,ContainerBuilder,TextDisplayBuilder,SeparatorBuilder,MessageFlags,Routes,UserSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,SectionBuilder,ThumbnailBuilder,MediaGalleryBuilder,MediaGalleryItemBuilder} from 'discord.js';
import {emojiFromLegacy,renderEmojis} from '../config/emojis';
export const V2_FLAG=MessageFlags.IsComponentsV2;
export function text(t:string){return new TextDisplayBuilder().setContent(renderEmojis(t))}
export function sep(){return new SeparatorBuilder().setDivider(true)}
export function btn(id:string,label:string,style=ButtonStyle.Secondary,emoji?:string){const b=new ButtonBuilder().setCustomId(id).setLabel(renderEmojis(label).slice(0,80)).setStyle(style);if(emoji)b.setEmoji(emojiFromLegacy(emoji));return b}
export function row(...b:ButtonBuilder[]){return new ActionRowBuilder<ButtonBuilder>().addComponents(...b)}
export function userSelectRow(id:string,placeholder='Chọn một đạo hữu'){const s=new UserSelectMenuBuilder().setCustomId(id).setPlaceholder(placeholder).setMinValues(1).setMaxValues(1);return new ActionRowBuilder<UserSelectMenuBuilder>().addComponents(s)}
export interface BoxMediaOptions{topImageUrl?:string;avatarUrl?:string}
export function box(title:string,body:string,rows:ActionRowBuilder<any>[]=[],media:BoxMediaOptions={}){const c=new ContainerBuilder().setAccentColor(0x8e44ad);if(media.topImageUrl){c.addMediaGalleryComponents(new MediaGalleryBuilder().addItems(new MediaGalleryItemBuilder().setURL(media.topImageUrl)))}const content=text(`# ${title}\n${body||'*Không có ghi chép.*'}`);if(media.avatarUrl){c.addSectionComponents(new SectionBuilder().addTextDisplayComponents(content).setThumbnailAccessory(new ThumbnailBuilder().setURL(media.avatarUrl).setDescription('Ảnh đại diện đạo hữu')))}else c.addTextDisplayComponents(content);for(const r of rows){c.addSeparatorComponents(sep());c.addActionRowComponents(r as any)}return c}

export interface BoxSection{title:string;rows:ActionRowBuilder<any>[]}
export function boxSections(title:string,body:string,sections:BoxSection[],media:BoxMediaOptions={}){
 const c=new ContainerBuilder().setAccentColor(0x8e44ad);
 if(media.topImageUrl)c.addMediaGalleryComponents(new MediaGalleryBuilder().addItems(new MediaGalleryItemBuilder().setURL(media.topImageUrl)));
 const content=text(`# ${title}\n${body||'*Không có ghi chép.*'}`);
 if(media.avatarUrl)c.addSectionComponents(new SectionBuilder().addTextDisplayComponents(content).setThumbnailAccessory(new ThumbnailBuilder().setURL(media.avatarUrl).setDescription('Ảnh đại diện đạo hữu')));else c.addTextDisplayComponents(content);
 for(const section of sections){c.addSeparatorComponents(sep());c.addTextDisplayComponents(text(`## ${section.title}`));for(const r of section.rows)c.addActionRowComponents(r as any)}
 return c;
}

export function sellModal(uid:string,preset=''){const m=new ModalBuilder().setCustomId(`ttmarketsellmodal_${uid}`).setTitle('Kim Vân Đài · Đăng bán');const item=new TextInputBuilder().setCustomId('item').setLabel('Tên, mã vật phẩm hoặc instance ID').setPlaceholder('Ví dụ: Thanh Linh Thảo').setStyle(TextInputStyle.Short).setRequired(true);if(preset)item.setValue(preset);const qty=new TextInputBuilder().setCustomId('qty').setLabel('Số lượng').setValue('1').setStyle(TextInputStyle.Short).setRequired(true);const price=new TextInputBuilder().setCustomId('price').setLabel('Tổng giá bán (Linh Thạch)').setPlaceholder('Ví dụ: 500').setStyle(TextInputStyle.Short).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(item),new ActionRowBuilder<TextInputBuilder>().addComponents(qty),new ActionRowBuilder<TextInputBuilder>().addComponents(price));return m}
export function auctionCreateModal(uid:string,instanceId:string){const m=new ModalBuilder().setCustomId(`ttauctioncreatemodal:${instanceId}_${uid}`).setTitle('Đấu Giá · Mở phiên');const price=new TextInputBuilder().setCustomId('price').setLabel('Giá khởi điểm (Linh Thạch)').setValue('1000').setStyle(TextInputStyle.Short).setRequired(true),hours=new TextInputBuilder().setCustomId('hours').setLabel('Thời hạn giờ (1–24)').setValue('6').setStyle(TextInputStyle.Short).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(price),new ActionRowBuilder<TextInputBuilder>().addComponents(hours));return m}
export function auctionBidModal(uid:string,listingId:number,min:number){const m=new ModalBuilder().setCustomId(`ttauctionbidmodal:${listingId}_${uid}`).setTitle('Đấu Giá · Ra giá');const amount=new TextInputBuilder().setCustomId('amount').setLabel(`Mức đặt tối thiểu ${min} LT`).setValue(String(min)).setStyle(TextInputStyle.Short).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(amount));return m}
export function appearanceModal(uid:string,field:'avatar_url'|'thumbnail_url'){const avatar=field==='avatar_url',m=new ModalBuilder().setCustomId(`ttappearancemodal:${field}_${uid}`).setTitle(avatar?'Hệ Thống · Đổi diện mạo':'Hệ Thống · Đổi ảnh nền');const url=new TextInputBuilder().setCustomId('url').setLabel(avatar?'Link ảnh diện mạo nhân vật':'Link ảnh nền hồ sơ').setPlaceholder('https://...').setStyle(TextInputStyle.Short).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(url));return m}
export function sectCreateModal(uid:string){const m=new ModalBuilder().setCustomId(`ttsectcreatemodal_${uid}`).setTitle('Khai Lập Tông Môn'),name=new TextInputBuilder().setCustomId('name').setLabel('Tên Tông Môn (2–24 ký tự)').setStyle(TextInputStyle.Short).setMinLength(2).setMaxLength(24).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(name));return m}
export function announcementModal(uid:string,pavilion:string){const m=new ModalBuilder().setCustomId(`ttannouncementmodal:${pavilion}_${uid}`).setTitle('Thiên Thư · Thiên Hạ Cáo Thị'),content=new TextInputBuilder().setCustomId('content').setLabel('Nội dung thông báo').setStyle(TextInputStyle.Paragraph).setMinLength(2).setMaxLength(1500).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(content));return m}
export function ownerAssetModal(uid:string,operation:string,asset:string){const m=new ModalBuilder().setCustomId(`ttownerassetmodal:${operation}~${asset}_${uid}`).setTitle(`Thiên Thư · ${operation} ${asset}`),target=new TextInputBuilder().setCustomId('target').setLabel('Discord User ID').setStyle(TextInputStyle.Short).setRequired(true),amount=new TextInputBuilder().setCustomId('amount').setLabel(operation==='SET'?'Số dư mới':'Số lượng').setStyle(TextInputStyle.Short).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(target),new ActionRowBuilder<TextInputBuilder>().addComponents(amount));return m}
export function ownerItemModal(uid:string,operation:string){const m=new ModalBuilder().setCustomId(`ttowneritemmodal:${operation}_${uid}`).setTitle(`Thiên Thư · ${operation} Item`),target=new TextInputBuilder().setCustomId('target').setLabel('Discord User ID').setStyle(TextInputStyle.Short).setRequired(true),item=new TextInputBuilder().setCustomId('item').setLabel('Item ID chính xác').setStyle(TextInputStyle.Short).setRequired(true),amount=new TextInputBuilder().setCustomId('amount').setLabel('Số lượng').setStyle(TextInputStyle.Short).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(target),new ActionRowBuilder<TextInputBuilder>().addComponents(item),new ActionRowBuilder<TextInputBuilder>().addComponents(amount));return m}
export function ownerPlayerModal(uid:string,action:string){const m=new ModalBuilder().setCustomId(`ttownerplayermodal:${action}_${uid}`).setTitle(`Thiên Thư · ${action}`),target=new TextInputBuilder().setCustomId('target').setLabel('Discord User ID').setStyle(TextInputStyle.Short).setRequired(true),value=new TextInputBuilder().setCustomId('value').setLabel(action==='SET_REALM'?'Realm ID (vd: nguyen_anh)':action==='SET_TUVI'?'Tu Vi tuyệt đối':'Nhập 1 để xác nhận').setValue(action.startsWith('LOCK')||action.startsWith('UNLOCK')?'1':'').setStyle(TextInputStyle.Short).setRequired(true),reason=new TextInputBuilder().setCustomId('reason').setLabel('Lý do').setStyle(TextInputStyle.Paragraph).setMinLength(3).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(target),new ActionRowBuilder<TextInputBuilder>().addComponents(value),new ActionRowBuilder<TextInputBuilder>().addComponents(reason));return m}
export function ownerContentModal(uid:string,action:string){const m=new ModalBuilder().setCustomId(`ttownercontentmodal:${action}_${uid}`).setTitle(`Thiên Thư · Content ${action}`),id=new TextInputBuilder().setCustomId('definition_id').setLabel('Definition ID').setStyle(TextInputStyle.Short).setRequired(true),kind=new TextInputBuilder().setCustomId('kind').setLabel(action==='DRAFT'?'Loại: item/monster/skill/...':'Version').setStyle(TextInputStyle.Short).setRequired(true),data=new TextInputBuilder().setCustomId('data').setLabel(action==='DRAFT'?'JSON definition':'Gõ CONFIRM').setStyle(TextInputStyle.Paragraph).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(id),new ActionRowBuilder<TextInputBuilder>().addComponents(kind),new ActionRowBuilder<TextInputBuilder>().addComponents(data));return m}
export function ownerRepairModal(uid:string){const m=new ModalBuilder().setCustomId(`ttownerrepairmodal_${uid}`).setTitle('Thiên Thư · Repair'),target=new TextInputBuilder().setCustomId('target').setLabel('Discord User ID').setStyle(TextInputStyle.Short).setRequired(true),field=new TextInputBuilder().setCustomId('field').setLabel('Field: hp / stamina / tu_vi').setStyle(TextInputStyle.Short).setRequired(true),value=new TextInputBuilder().setCustomId('value').setLabel('Giá trị sau repair').setStyle(TextInputStyle.Short).setRequired(true),reason=new TextInputBuilder().setCustomId('reason').setLabel('Reason | provenance').setStyle(TextInputStyle.Paragraph).setRequired(true),key=new TextInputBuilder().setCustomId('key').setLabel('Idempotency key (ít nhất 8 ký tự)').setStyle(TextInputStyle.Short).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(target),new ActionRowBuilder<TextInputBuilder>().addComponents(field),new ActionRowBuilder<TextInputBuilder>().addComponents(value),new ActionRowBuilder<TextInputBuilder>().addComponents(reason),new ActionRowBuilder<TextInputBuilder>().addComponents(key));return m}
export async function safeUpdate(i:any,c:ContainerBuilder){await i.client.rest.post(Routes.interactionCallback(i.id,i.token),{body:{type:7,data:{components:[c],flags:V2_FLAG}}});i.replied=true}
