import {ActionRowBuilder,ButtonBuilder,ButtonStyle,ContainerBuilder,TextDisplayBuilder,SeparatorBuilder,MessageFlags,Routes,UserSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,SectionBuilder,ThumbnailBuilder,MediaGalleryBuilder,MediaGalleryItemBuilder} from 'discord.js';
export const V2_FLAG=MessageFlags.IsComponentsV2;
export function text(t:string){return new TextDisplayBuilder().setContent(t)}
export function sep(){return new SeparatorBuilder().setDivider(true)}
export function btn(id:string,label:string,style=ButtonStyle.Secondary,emoji?:string){const b=new ButtonBuilder().setCustomId(id).setLabel(label.slice(0,80)).setStyle(style);if(emoji)b.setEmoji(emoji);return b}
export function row(...b:ButtonBuilder[]){return new ActionRowBuilder<ButtonBuilder>().addComponents(...b)}
export function userSelectRow(id:string,placeholder='Chọn một đạo hữu'){const s=new UserSelectMenuBuilder().setCustomId(id).setPlaceholder(placeholder).setMinValues(1).setMaxValues(1);return new ActionRowBuilder<UserSelectMenuBuilder>().addComponents(s)}
export interface BoxMediaOptions{topImageUrl?:string;avatarUrl?:string}
export function box(title:string,body:string,rows:ActionRowBuilder<any>[]=[],media:BoxMediaOptions={}){const c=new ContainerBuilder().setAccentColor(0x8e44ad);if(media.topImageUrl){c.addMediaGalleryComponents(new MediaGalleryBuilder().addItems(new MediaGalleryItemBuilder().setURL(media.topImageUrl)))}const content=text(`# ${title}\n${body||'*Không có ghi chép.*'}`);if(media.avatarUrl){c.addSectionComponents(new SectionBuilder().addTextDisplayComponents(content).setThumbnailAccessory(new ThumbnailBuilder().setURL(media.avatarUrl).setDescription('Ảnh đại diện đạo hữu')))}else c.addTextDisplayComponents(content);for(const r of rows){c.addSeparatorComponents(sep());c.addActionRowComponents(r as any)}return c}
export function sellModal(uid:string){const m=new ModalBuilder().setCustomId(`ttmarketsellmodal_${uid}`).setTitle('Kim Vân Đài · Đăng bán');const item=new TextInputBuilder().setCustomId('item').setLabel('Tên hoặc mã vật phẩm').setPlaceholder('Ví dụ: Thanh Linh Thảo').setStyle(TextInputStyle.Short).setRequired(true);const qty=new TextInputBuilder().setCustomId('qty').setLabel('Số lượng').setValue('1').setStyle(TextInputStyle.Short).setRequired(true);const price=new TextInputBuilder().setCustomId('price').setLabel('Tổng giá bán (Linh Thạch)').setPlaceholder('Ví dụ: 500').setStyle(TextInputStyle.Short).setRequired(true);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(item),new ActionRowBuilder<TextInputBuilder>().addComponents(qty),new ActionRowBuilder<TextInputBuilder>().addComponents(price));return m}
export async function safeUpdate(i:any,c:ContainerBuilder){i.replied=true;await i.client.rest.post(Routes.interactionCallback(i.id,i.token),{body:{type:7,data:{components:[c],flags:V2_FLAG}}})}
