import {auditCatalog,ITEMS,LOCATIONS,RECIPES,BOSSES,SECRET_REALMS,REALMS} from './config/GameCatalog';
import {auditSystemAccess,FEATURES,UI_ACTIONS} from './config/SystemRegistry';
import {auditRareFireCatalog,RARE_FIRES} from './config/RareFireCatalog';
import {auditJourneyCatalog} from './config/JourneyCatalog';
import {auditProductionJourneys,PRODUCTION_JOURNEYS} from './config/JourneyProductionCatalog';
import {auditJourneyRegistry,JOURNEY_REGISTRY} from './config/JourneyRegistry';
import {storageService} from './services/StorageService';
import {itemInstanceService} from './services/ItemInstanceService';
import db,{initDatabase} from './database/database';
import {auditRuntimeCatalog} from './config/RuntimeCatalog';
import {auditRuntimeTables} from './services/RuntimeSystemsService';
import {auditCombatCatalog} from './config/CombatCatalog';
import {ANOMALIES,auditActivityCatalog,RARE_DUTIES} from './config/ActivityCatalog';
import {contentResolver} from './services/RuntimeKernelService';
import {towerService} from './services/TowerService';
import {EMOJIS} from './config/emojis';
import {ITEM_NAMES} from './config/ItemNames';
import {runStartupAudit} from './services/StartupAuditService';
import {realmNpcVisitService} from './services/RealmNpcVisitService';

initDatabase();
const materializedTables=['operation_receipts','runtime_leases','outbox_events','content_pins','combat_encounters','combat_events','combat_settlements','dungeon_runs','dungeon_room_receipts','player_sects','player_sect_buildings','player_sect_warehouse','partner_bonds','dual_cultivation_sessions','mentorship_bonds','guidance_receipts','npc_companion_states','rare_duty_states','rare_duty_evidence','anomaly_runs','world_merit_ledger','tower_runs','tower_floor_receipts','realm_npc_visits','onboarding_milestones','player_credentials','interaction_receipts','interaction_rate_limits'];
const materialized=materializedTables.filter(t=>!db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(t)).map(t=>`${t}: missing materialized table`);
const catalog=auditCatalog(),access=auditSystemAccess(),fires=auditRareFireCatalog(),journeys=[...auditJourneyCatalog(),...auditJourneyRegistry(),...auditProductionJourneys()],storage=storageService.audit(),instances=itemInstanceService.audit(),runtime=[...auditRuntimeCatalog(),...auditRuntimeTables(),...auditCombatCatalog(),...auditActivityCatalog(),...contentResolver.audit(),...towerService.audit(),...realmNpcVisitService.audit(),...materialized];
const startup=runStartupAudit(['taonhanvat','thienthu','tutien']);
console.log(`Cảnh giới: ${REALMS.length}`);console.log(`Vật phẩm: ${Object.keys(ITEMS).length}`);console.log(`Địa vực: ${LOCATIONS.length}`);console.log(`Công thức: ${RECIPES.length}`);console.log(`Dị Hỏa: ${RARE_FIRES.length}`);console.log(`Cường địch: ${BOSSES.length}`);console.log(`Bí cảnh: ${SECRET_REALMS.length}`);console.log(`Cơ Duyên registry: ${JOURNEY_REGISTRY.length} · playable: ${PRODUCTION_JOURNEYS.length}`);console.log(`Hệ thống có lối vào: ${FEATURES.length}/${FEATURES.length}`);console.log(`UI actions: ${UI_ACTIONS.length}`);console.log(`Nghĩa vụ cực hiếm: ${RARE_DUTIES.length}`);console.log(`Dị tượng authored: ${ANOMALIES.length}`);console.log(`Runtime materialized tables: ${materializedTables.length-materialized.length}/${materializedTables.length}`);
console.log(`Emoji registry: ${Object.keys(EMOJIS).length} semantic keys`);console.log(`Item name registry: ${Object.keys(ITEM_NAMES).length}/${Object.keys(ITEMS).length}`);
console.log(`Production startup: ${startup.checks} checks · ${startup.commands.length} slash commands`);
if(catalog.length||access.length||fires.length||journeys.length||storage.length||instances.length||runtime.length||!startup.ok){console.error([...catalog,...access,...fires,...journeys,...storage,...instances,...runtime,...startup.errors].join('\n'));process.exit(1)}console.log('✅ Audit hoàn tất: catalog, content graph và materialized runtime không có dependency bị đứt.');
