import fs from 'fs';import path from 'path';
const dbPath=path.join(process.cwd(),'data','item-instance-test.sqlite');fs.mkdirSync(path.dirname(dbPath),{recursive:true});for(const f of [dbPath,dbPath+'-wal',dbPath+'-shm'])try{fs.unlinkSync(f)}catch{}process.env.DB_PATH=dbPath;
const {initDatabase}=require('./database/database');const db=require('./database/database').default;const {userRepository}=require('./database/repositories/UserRepository');const {inventoryRepository}=require('./database/repositories/InventoryRepository');const {itemInstanceService}=require('./services/ItemInstanceService');const {marketService}=require('./services/MarketService');const {cultivationService}=require('./services/CultivationService');const {HEIRLOOMS}=require('./data/creationLore');const {ITEMS}=require('./config/GameCatalog');
function ok(v:any,m:string){if(!v)throw new Error(m)}
initDatabase();
userRepository.create('family','Gia Tộc');let grant=itemInstanceService.grantCreation('family','tu_chien_gia_toc',HEIRLOOMS[0]);ok(grant.gift.template_id==='gia_truyen_kiem'&&grant.gift.binding==='SOULBOUND','family sword instance');ok(itemInstanceService.equip('family',grant.gift.instance_id).ok,'equip instance');ok(itemInstanceService.stats('family').atk>0,'instance stats active');ok(itemInstanceService.damage('family',grant.gift.instance_id,30).ok&&itemInstanceService.get(grant.gift.instance_id).durability===70,'durability loss');db.prepare('UPDATE users SET coin_ha_pham=1000 WHERE discord_id=?').run('family');ok(itemInstanceService.repair('family',grant.gift.instance_id).ok&&itemInstanceService.get(grant.gift.instance_id).durability===100,'repair sink');ok(itemInstanceService.stats('family').atkPct===0,'dormant heirloom no effect');ok(itemInstanceService.identifyHeirloom('family',grant.heirloom.instance_id).ok,'identify heirloom');ok(itemInstanceService.stats('family').atkPct===.01,'identified heirloom effect');
userRepository.create('survivor','Kỳ Ngộ');grant=itemInstanceService.grantCreation('survivor','ky_ngo_sinh_tu',HEIRLOOMS[1]);ok(grant.gift.template_id==='manh_ngoc_ho_menh'&&grant.gift.state==='INTACT','jade instance');ok(itemInstanceService.stats('survivor').defPct===.02,'intact ward passive');ok(itemInstanceService.triggerWard('survivor'),'ward trigger');ok(itemInstanceService.stats('survivor').defPct===0,'cracked ward inactive');db.prepare('UPDATE users SET coin_ha_pham=500 WHERE discord_id=?').run('survivor');ok(itemInstanceService.restoreWard('survivor',grant.gift.instance_id).ok,'ward restoration sink');
userRepository.create('wanderer','Tán Tu');itemInstanceService.grantCreation('wanderer','de_tu_tan_tu',HEIRLOOMS[2]);ok(!!db.prepare("SELECT 1 FROM knowledge_provenance WHERE user_id='wanderer' AND fact_key='manual:sach_khai_kinh'").get(),'manual becomes knowledge');ok(!db.prepare("SELECT 1 FROM item_instances WHERE owner_id='wanderer' AND template_id='sach_khai_kinh'").get(),'manual not dead inventory item');ok(cultivationService.meditate('wanderer').message.includes('Sách Khai Kinh'),'manual has real cultivation resolver');
userRepository.create('jade-owner','Cổ Ngọc');const jade=itemInstanceService.createHeirloom('jade-owner',HEIRLOOMS[1]);ok(itemInstanceService.identifyHeirloom('jade-owner',jade.instance_id).ok,'identify cultivation heirloom');ok(cultivationService.addTuVi('jade-owner',100).gained===101,'heirloom cultivation effect resolved');
userRepository.create('full','Đầy Túi');const mats=Object.values(ITEMS).filter((x:any)=>x.type==='material').slice(0,12) as any[];for(const x of mats)inventoryRepository.add('full',x.id,1);const overflow=itemInstanceService.create('full','gia_truyen_kiem','weapon',{source:'TEST'},{binding:'SOULBOUND'});ok(overflow.location==='TEMPORARY','instance overflow');db.prepare('UPDATE item_instances SET temporary_expires_at=0 WHERE instance_id=?').run(overflow.instance_id);itemInstanceService.sweepTemporary('full');ok(itemInstanceService.get(overflow.instance_id).location==='VAULT','protected instance expiry to vault');inventoryRepository.remove('full',mats[0].id,1);ok(itemInstanceService.claim('full',overflow.instance_id).ok,'claim instance after free slot');
userRepository.create('legacy','Legacy');db.prepare("INSERT INTO inventories(user_id,item_id,quantity,is_equipped) VALUES('legacy','weapon_0',2,1)").run();initDatabase();ok((db.prepare("SELECT COUNT(*) n FROM item_instances WHERE owner_id='legacy' AND template_id='weapon_0'").get() as any).n===2,'legacy equipment split into instances');ok(!db.prepare("SELECT 1 FROM inventories WHERE user_id='legacy' AND item_id='weapon_0'").get(),'legacy stack removed');ok((db.prepare("SELECT COUNT(*) n FROM item_instance_history WHERE owner_id IN ('family','survivor')").get() as any).n>=8,'provenance history persisted');
userRepository.create('instance-seller','Instance Seller');userRepository.create('instance-buyer','Instance Buyer');const traded=itemInstanceService.create('instance-seller','weapon_0','weapon',{source:'CRAFT'},{binding:'UNBOUND'});ok(marketService.create('instance-seller',traded.instance_id,1,50).ok,'instance enters escrow');const listing=db.prepare("SELECT id FROM market_listings WHERE instance_id=? AND status='active'").get(traded.instance_id) as any;ok(marketService.buy('instance-buyer',listing.id).ok,'instance market purchase');ok(itemInstanceService.get(traded.instance_id).owner_id==='instance-buyer','instance ownership transferred');ok(userRepository.get('instance-seller').coin_ha_pham===148,'instance market 5% fee');
console.log('✅ Item instance runtime: vật truyền/Cổ vật/độ bền/tu bổ/hộ mệnh/Knowledge/overflow/migration PASS');
